----------
--ESTRAL--
----------

BU = BU or {}

BU.Bundles = {
    ["BundleUp.IronPipesLR"]                        = { base = "Base.MetalPipe", count = 10 },
    ["BundleUp.IronPipesLSR"]                       = { base = "Base.MetalPipe", count = 10 },
    ["BundleUp.IronPipesR"]                         = { base = "Base.MetalPipe", count = 5 },
    ["BundleUp.IronPipesSR"]                        = { base = "Base.MetalPipe", count = 5 },
    ["BundleUp.PlankLR"]                            = { base = "Base.Plank", count = 10 },
    ["BundleUp.PlankLSR"]                           = { base = "Base.Plank", count = 10 },
    ["BundleUp.PlankR"]                             = { base = "Base.Plank", count = 5 },
    ["BundleUp.PlankSR"]                            = { base = "Base.Plank", count = 5 },
    ["BundleUp.SheetMetalLR"]                       = { base = "Base.SheetMetal", count = 10 },
    ["BundleUp.SheetMetalLSR"]                      = { base = "Base.SheetMetal", count = 10 },
    ["BundleUp.SheetMetalR"]                        = { base = "Base.SheetMetal", count = 5 },
    ["BundleUp.SheetMetalSR"]                       = { base = "Base.SheetMetal", count = 5 },
    ["BundleUp.NailsBox_Medium"]                    = { base = "Base.Nails", count = 50 },
    ["BundleUp.NailsBox_Small"]                     = { base = "Base.Nails", count = 25 },
    ["BundleUp.PenBox_Black"]                       = { base = "Base.Pen", count = 10 },
    ["BundleUp.PenBox_Blue"]                        = { base = "Base.BluePen", count = 10 },
    ["BundleUp.PenBox_Red"]                         = { base = "Base.RedPen", count = 10 },
    ["BundleUp.ScrewsBox_Medium"]                   = { base = "Base.Screws", count = 50 },
    ["BundleUp.ScrewsBox_Small"]                    = { base = "Base.Screws", count = 25 },
    ["BundleUp.SmallMetalSheetL"]                   = { base = "Base.SmallSheetMetal", count = 10 },
    ["BundleUp.SmallMetalSheetS"]                   = { base = "Base.SmallSheetMetal", count = 5 },
    ["BundleUp.WireCable_Large"]                    = { base = "Base.Wire", count = 10 },
    ["BundleUp.WireCable_Small"]                    = { base = "Base.Wire", count = 5 },
    ["BundleUp.ElectronicsScrapSack"]               = { base = "Base.ElectronicsScrap", count = 25 },
    ["BundleUp.Sack_Sack"]                          = { base = "Base.EmptySandbag", count = 5 },
    ["BundleUp.ScrapMetalSack"]                     = { base = "Base.ScrapMetal", count = 25 },
    ["BundleUp.UnusableWoodSack"]                   = { base = "Base.UnusableWood", count = 25 },
    ["BundleUp.AlcoholBandageBox"]                  = { base = "Base.AlcoholBandage", count = 10 },
    ["BundleUp.AlcoholWipesBox"]                    = { base = "Base.AlcoholWipes", count = 10 },
    ["BundleUp.AlcoholedCottonBallsBox"]            = { base = "Base.AlcoholedCottonBalls", count = 10 },
    ["BundleUp.PillsAntiDepBox"]                    = { base = "Base.PillsAntiDep", count = 10 },
    ["BundleUp.PillsBetaBox"]                       = { base = "Base.PillsBeta", count = 10 },
    ["BundleUp.PillsBox"]                           = { base = "Base.Pills", count = 10 },
    ["BundleUp.PillsSleepingTabletsBox"]            = { base = "Base.PillsSleepingTablets", count = 10 },
    ["BundleUp.PillsVitaminsBox"]                   = { base = "Base.PillsVitamins", count = 10 },
    ["BundleUp.TissueBox"]                          = { base = "Base.Tissue", count = 10 },
    ["BundleUp.BeefJerkyCarton"]                    = { base = "Base.BeefJerky", count = 12 },
    ["BundleUp.BellPepperCarton"]                   = { base = "Base.BellPepper", count = 12 },
    ["BundleUp.BroccoliCarton"]                     = { base = "Base.Broccoli", count = 12 },
    ["BundleUp.ButterCarton"]                       = { base = "Base.Butter", count = 12 },
    ["BundleUp.CabbageCarton"]                      = { base = "farming.Cabbage", count = 12 },
    ["BundleUp.CandyCornCarton"]                    = { base = "Base.CandyCorn", count = 12 },
    ["BundleUp.CandyFruitSlicesCarton"]             = { base = "Base.CandyFruitSlices", count = 12 },
    ["BundleUp.CandycaneCarton"]                    = { base = "Base.Candycane", count = 12 },
    ["BundleUp.CarrotsCarton"]                      = { base = "Base.Carrots", count = 12 },
    ["BundleUp.CerealCarton"]                       = { base = "Base.Cereal", count = 12 },
    ["BundleUp.CheeseCarton"]                       = { base = "Base.Cheese", count = 12 },
    ["BundleUp.ChocoCakesCarton"]                   = { base = "Base.ChocoCakes", count = 12 },
    ["BundleUp.ChocolateCarton"]                    = { base = "Base.Chocolate", count = 12 },
    ["BundleUp.ChocolateChipsCarton"]               = { base = "Base.ChocolateChips", count = 12 },
    ["BundleUp.ChocolateCoveredCoffeeBeansCarton"]  = { base = "Base.ChocolateCoveredCoffeeBeans", count = 12 },
    ["BundleUp.CinnamonRollCarton"]                 = { base = "Base.CinnamonRoll", count = 12 },
    ["BundleUp.CocoaPowderCarton"]                  = { base = "Base.CocoaPowder", count = 12 },
    ["BundleUp.Coffee2Carton"]                      = { base = "Base.Coffee2", count = 12 },
    ["BundleUp.CookieChocolateChipCarton"]          = { base = "Base.CookieChocolateChip", count = 12 },
    ["BundleUp.CookieJellyCarton"]                  = { base = "Base.CookieJelly", count = 12 },
    ["BundleUp.CookiesChocolateCarton"]             = { base = "Base.CookiesChocolate", count = 12 },
    ["BundleUp.CookiesOatmealCarton"]               = { base = "Base.CookiesOatmeal", count = 12 },
    ["BundleUp.CookiesShortbreadCarton"]            = { base = "Base.CookiesShortbread", count = 12 },
    ["BundleUp.CookiesSugarCarton"]                 = { base = "Base.CookiesSugar", count = 12 },
    ["BundleUp.CornCarton"]                         = { base = "Base.Corn", count = 12 },
    ["BundleUp.CrackersCarton"]                     = { base = "Base.Crackers", count = 12 },
    ["BundleUp.Crisps2Carton"]                      = { base = "Base.Crisps2", count = 12 },
    ["BundleUp.Crisps3Carton"]                      = { base = "Base.Crisps3", count = 12 },
    ["BundleUp.Crisps4Carton"]                      = { base = "Base.Crisps4", count = 12 },
    ["BundleUp.CrispsCarton"]                       = { base = "Base.Crisps", count = 12 },
    ["BundleUp.DehydratedMeatStickCarton"]          = { base = "Base.DehydratedMeatStick", count = 12 },
    ["BundleUp.DriedBlackBeansCarton"]              = { base = "Base.DriedBlackBeans", count = 12 },
    ["BundleUp.DriedChickpeasCarton"]               = { base = "Base.DriedChickpeas", count = 12 },
    ["BundleUp.DriedKidneyBeansCarton"]             = { base = "Base.DriedKidneyBeans", count = 12 },
    ["BundleUp.DriedLentilsCarton"]                 = { base = "Base.DriedLentils", count = 12 },
    ["BundleUp.DriedSplitPeasCarton"]               = { base = "Base.DriedSplitPeas", count = 12 },
    ["BundleUp.DriedWhiteBeansCarton"]              = { base = "Base.DriedWhiteBeans", count = 12 },
    ["BundleUp.EggplantCarton"]                     = { base = "Base.Eggplant", count = 12 },
    ["BundleUp.GinsengCarton"]                      = { base = "Base.Ginseng", count = 12 },
    ["BundleUp.GrahamCrackersCarton"]               = { base = "Base.GrahamCrackers", count = 12 },
    ["BundleUp.GranolaBarCarton"]                   = { base = "Base.GranolaBar", count = 12 },
    ["BundleUp.GumCarton"]                          = { base = "Base.Gum", count = 12 },
    ["BundleUp.GummyBearsCarton"]                   = { base = "Base.GummyBears", count = 12 },
    ["BundleUp.GummyWormsCarton"]                   = { base = "Base.GummyWorms", count = 12 },
    ["BundleUp.HardCandiesCarton"]                  = { base = "Base.HardCandies", count = 12 },
    ["BundleUp.HiHisCarton"]                        = { base = "Base.HiHis", count = 12 },
    ["BundleUp.HoneyCarton"]                        = { base = "Base.Honey", count = 12 },
    ["BundleUp.HotsauceCarton"]                     = { base = "Base.Hotsauce", count = 12 },
    ["BundleUp.JamFruitCarton"]                     = { base = "Base.JamFruit", count = 12 },
    ["BundleUp.JamMarmaladeCarton"]                 = { base = "Base.JamMarmalade", count = 12 },
    ["BundleUp.JellyBeansCarton"]                   = { base = "Base.JellyBeans", count = 12 },
    ["BundleUp.JujubesCarton"]                      = { base = "Base.Jujubes", count = 12 },
    ["BundleUp.KetchupCarton"]                      = { base = "Base.Ketchup", count = 12 },
    ["BundleUp.LardCarton"]                         = { base = "Base.Lard", count = 12 },
    ["BundleUp.LeekCarton"]                         = { base = "Base.Leek", count = 12 },
    ["BundleUp.LettuceCarton"]                      = { base = "Base.Lettuce", count = 12 },
    ["BundleUp.LicoriceBlackCarton"]                = { base = "Base.LicoriceBlack", count = 12 },
    ["BundleUp.LicoriceRedCarton"]                  = { base = "Base.LicoriceRed", count = 12 },
    ["BundleUp.MapleSyrupCarton"]                   = { base = "Base.MapleSyrup", count = 12 },
    ["BundleUp.MargarineCarton"]                    = { base = "Base.Margarine", count = 12 },
    ["BundleUp.MarinaraCarton"]                     = { base = "Base.Marinara", count = 12 },
    ["BundleUp.MarshmallowsCarton"]                 = { base = "Base.Marshmallows", count = 12 },
    ["BundleUp.MayonnaiseFullCarton"]               = { base = "farming.MayonnaiseFull", count = 12 },
    ["BundleUp.MustardCarton"]                      = { base = "Base.Mustard", count = 12 },
    ["BundleUp.OatsRawCarton"]                      = { base = "Base.OatsRaw", count = 12 },
    ["BundleUp.OilOliveCarton"]                     = { base = "Base.OilOlive", count = 12 },
    ["BundleUp.OilVegetableCarton"]                 = { base = "Base.OilVegetable", count = 12 },
    ["BundleUp.OnionCarton"]                        = { base = "Base.Onion", count = 12 },
    ["BundleUp.PastaCarton"]                        = { base = "Base.Pasta", count = 12 },
    ["BundleUp.PeanutButterCarton"]                 = { base = "Base.PeanutButter", count = 12 },
    ["BundleUp.PepperCarton"]                       = { base = "Base.Pepper", count = 12 },
    ["BundleUp.PepperHabaneroCarton"]               = { base = "Base.PepperHabanero", count = 12 },
    ["BundleUp.PepperJalapenoCarton"]               = { base = "Base.PepperJalapeno", count = 12 },
    ["BundleUp.PicklesCarton"]                      = { base = "Base.Pickles", count = 12 },
    ["BundleUp.PlonkiesCarton"]                     = { base = "Base.Plonkies", count = 12 },
    ["BundleUp.PopcornCarton"]                      = { base = "Base.Popcorn", count = 12 },
    ["BundleUp.PotatoCarton"]                       = { base = "farming.Potato", count = 12 },
    ["BundleUp.PretzelCarton"]                      = { base = "Base.Pretzel", count = 12 },
    ["BundleUp.QuaggaCakesCarton"]                  = { base = "Base.QuaggaCakes", count = 12 },
    ["BundleUp.RamenCarton"]                        = { base = "Base.Ramen", count = 12 },
    ["BundleUp.RedRadishCarton"]                    = { base = "farming.RedRadish", count = 12 },
    ["BundleUp.RemouladeFullCarton"]                = { base = "farming.RemouladeFull", count = 12 },
    ["BundleUp.RiceCarton"]                         = { base = "Base.Rice", count = 12 },
    ["BundleUp.RiceVinegarCarton"]                  = { base = "Base.RiceVinegar", count = 12 },
    ["BundleUp.RockCandyCarton"]                    = { base = "Base.RockCandy", count = 12 },
    ["BundleUp.SalamiCarton"]                       = { base = "Base.Salami", count = 12 },
    ["BundleUp.SaltCarton"]                         = { base = "Base.Salt", count = 12 },
    ["BundleUp.SnoGlobesCarton"]                    = { base = "Base.SnoGlobes", count = 12 },
    ["BundleUp.SoysauceCarton"]                     = { base = "Base.Soysauce", count = 12 },
    ["BundleUp.SugarBrownCarton"]                   = { base = "Base.SugarBrown", count = 12 },
    ["BundleUp.SugarCarton"]                        = { base = "Base.Sugar", count = 12 },
    ["BundleUp.Teabag2Carton"]                      = { base = "Base.Teabag2", count = 12 },
    ["BundleUp.TomatoCarton"]                       = { base = "farming.Tomato", count = 12 },
    ["BundleUp.TomatoPasteCarton"]                  = { base = "Base.TomatoPaste", count = 12 },
    ["BundleUp.TortillaChipsCarton"]                = { base = "Base.TortillaChips", count = 12 },
    ["BundleUp.WildEggsCarton"]                     = { base = "Base.WildEggs", count = 12 },
    ["BundleUp.YoghurtCarton"]                      = { base = "Base.Yoghurt", count = 12 },
    ["BundleUp.ZucchiniCarton"]                     = { base = "Base.Zucchini", count = 12 },
    ["BundleUp.AluminumBox"]                        = { base = "Base.Aluminum", count = 10 },
    ["BundleUp.AmplifierBox"]                       = { base = "Base.Amplifier", count = 10 },
    ["BundleUp.BakingSodaBox"]                      = { base = "Base.BakingSoda", count = 10 },
    ["BundleUp.ButterKnifeBox"]                     = { base = "Base.ButterKnife", count = 10 },
    ["BundleUp.ButtonBox"]                          = { base = "Base.Button", count = 10 },
    ["BundleUp.DoorknobBox"]                        = { base = "Base.Doorknob", count = 10 },
    ["BundleUp.ElectricWireBox"]                    = { base = "Radio.ElectricWire", count = 10 },
    ["BundleUp.FishingLineBox"]                     = { base = "Base.FishingLine", count = 10 },
    ["BundleUp.ForkBox"]                            = { base = "Base.Fork", count = 10 },
    ["BundleUp.GlueBox"]                            = { base = "Base.Glue", count = 10 },
    ["BundleUp.GravyMixBox"]                        = { base = "Base.GravyMix", count = 10 },
    ["BundleUp.HairgelBox"]                         = { base = "Base.Hairgel", count = 10 },
    ["BundleUp.HingeBox"]                           = { base = "Base.Hinge", count = 10 },
    ["BundleUp.JarLidBox"]                          = { base = "Base.JarLid", count = 10 },
    ["BundleUp.LightBulbBlueBox"]                   = { base = "Base.LightBulbBlue", count = 10 },
    ["BundleUp.LightBulbCyanBox"]                   = { base = "Base.LightBulbCyan", count = 10 },
    ["BundleUp.LightBulbGreenBox"]                  = { base = "Base.LightBulbGreen", count = 10 },
    ["BundleUp.LightBulbMagentaBox"]                = { base = "Base.LightBulbMagenta", count = 10 },
    ["BundleUp.LightBulbOrangeBox"]                 = { base = "Base.LightBulbOrange", count = 10 },
    ["BundleUp.LightBulbPinkBox"]                   = { base = "Base.LightBulbPink", count = 10 },
    ["BundleUp.LightBulbPurpleBox"]                 = { base = "Base.LightBulbPurple", count = 10 },
    ["BundleUp.LightBulbRedBox"]                    = { base = "Base.LightBulbRed", count = 10 },
    ["BundleUp.LightBulbYellowBox"]                 = { base = "Base.LightBulbYellow", count = 10 },
    ["BundleUp.LighterBox"]                         = { base = "Base.Lighter", count = 10 },
    ["BundleUp.MakeupEyeshadowBox"]                 = { base = "Base.MakeupEyeshadow", count = 10 },
    ["BundleUp.MakeupFoundationBox"]                = { base = "Base.MakeupFoundation", count = 10 },
    ["BundleUp.MatchesBox"]                         = { base = "Base.Matches", count = 10 },
    ["BundleUp.MotionSensorBox"]                    = { base = "Base.MotionSensor", count = 10 },
    ["BundleUp.PancakeMixBox"]                      = { base = "Base.PancakeMix", count = 10 },
    ["BundleUp.PaperclipBoxCrate"]                  = { base = "Base.PaperclipBox", count = 10 },
    ["BundleUp.PillowBox"]                          = { base = "Base.Pillow", count = 10 },
    ["BundleUp.RadioReceiverBox"]                   = { base = "Radio.RadioReceiver", count = 10 },
    ["BundleUp.RadioTransmitterBox"]                = { base = "Radio.RadioTransmitter", count = 10 },
    ["BundleUp.ReceiverBox"]                        = { base = "Base.Receiver", count = 10 },
    ["BundleUp.RemoteBox"]                          = { base = "Base.Remote", count = 10 },
    ["BundleUp.Soap2Box"]                           = { base = "Base.Soap2", count = 10 },
    ["BundleUp.SparklersBox"]                       = { base = "Base.Sparklers", count = 10 },
    ["BundleUp.SpongeBox"]                          = { base = "Base.Sponge", count = 10 },
    ["BundleUp.SpoonBox"]                           = { base = "Base.Spoon", count = 10 },
    ["BundleUp.TarpBox"]                            = { base = "Base.Tarp", count = 10 },
    ["BundleUp.TimerBox"]                           = { base = "Base.Timer", count = 10 },
    ["BundleUp.TimerCraftedBox"]                    = { base = "Base.TimerCrafted", count = 10 },
    ["BundleUp.ToiletPaperBox"]                     = { base = "Base.ToiletPaper", count = 10 },
    ["BundleUp.ToothbrushBox"]                      = { base = "Base.Toothbrush", count = 10 },
    ["BundleUp.TriggerCraftedBox"]                  = { base = "Base.TriggerCrafted", count = 10 },
    ["BundleUp.TwineBox"]                           = { base = "Base.Twine", count = 10 },
    ["BundleUp.WeldingRodsBox"]                     = { base = "Base.WeldingRods", count = 10 },
    ["BundleUp.WoodglueBox"]                        = { base = "Base.Woodglue", count = 10 },
    ["BundleUp.YeastBox"]                           = { base = "Base.Yeast", count = 10 },
}

BU.BaseCategory = {
    ["Base.AlcoholBandage"]       = "ReductionMedical",
    ["Base.AlcoholWipes"]         = "ReductionMedical",
    ["Base.AlcoholedCottonBalls"] = "ReductionMedical",
    ["Base.Aluminum"]             = "ReductionOther",
    ["Base.Amplifier"]            = "ReductionOther",
    ["Base.BakingSoda"]           = "ReductionOther",
    ["Base.BeefJerky"]            = "ReductionFood",
    ["Base.BellPepper"]           = "ReductionFood",
    ["Base.Broccoli"]             = "ReductionFood",
    ["Base.Butter"]               = "ReductionFood",
    ["Base.ButterKnife"]          = "ReductionOther",
    ["Base.Button"]               = "ReductionOther",
    ["Base.CandyCorn"]            = "ReductionFood",
    ["Base.CandyFruitSlices"]     = "ReductionFood",
    ["Base.Candycane"]            = "ReductionFood",
    ["Base.Carrots"]              = "ReductionFood",
    ["Base.Cereal"]               = "ReductionFood",
    ["Base.Cheese"]               = "ReductionFood",
    ["Base.ChocoCakes"]           = "ReductionFood",
    ["Base.Chocolate"]            = "ReductionFood",
    ["Base.ChocolateChips"]       = "ReductionFood",
    ["Base.ChocolateCoveredCoffeeBeans"] = "ReductionFood",
    ["Base.CinnamonRoll"]         = "ReductionFood",
    ["Base.CocoaPowder"]          = "ReductionFood",
    ["Base.Coffee2"]              = "ReductionFood",
    ["Base.CookieChocolateChip"]  = "ReductionFood",
    ["Base.CookieJelly"]          = "ReductionFood",
    ["Base.CookiesChocolate"]     = "ReductionFood",
    ["Base.CookiesOatmeal"]       = "ReductionFood",
    ["Base.CookiesShortbread"]    = "ReductionFood",
    ["Base.CookiesSugar"]         = "ReductionFood",
    ["Base.Corn"]                 = "ReductionFood",
    ["Base.Crackers"]             = "ReductionFood",
    ["Base.Crisps"]               = "ReductionFood",
    ["Base.Crisps2"]              = "ReductionFood",
    ["Base.Crisps3"]              = "ReductionFood",
    ["Base.Crisps4"]              = "ReductionFood",
    ["Base.DehydratedMeatStick"]  = "ReductionFood",
    ["Base.Doorknob"]             = "ReductionOther",
    ["Base.DriedBlackBeans"]      = "ReductionFood",
    ["Base.DriedChickpeas"]       = "ReductionFood",
    ["Base.DriedKidneyBeans"]     = "ReductionFood",
    ["Base.DriedLentils"]         = "ReductionFood",
    ["Base.DriedSplitPeas"]       = "ReductionFood",
    ["Base.DriedWhiteBeans"]      = "ReductionFood",
    ["Base.Eggplant"]             = "ReductionFood",
    ["Base.ElectronicsScrap"]     = "ReductionMetal",
    ["Base.FishingLine"]          = "ReductionOther",
    ["Base.Fork"]                 = "ReductionOther",
    ["Base.Ginseng"]              = "ReductionFood",
    ["Base.Glue"]                 = "ReductionOther",
    ["Base.GrahamCrackers"]       = "ReductionFood",
    ["Base.GranolaBar"]           = "ReductionFood",
    ["Base.GravyMix"]             = "ReductionOther",
    ["Base.Gum"]                  = "ReductionFood",
    ["Base.GummyBears"]           = "ReductionFood",
    ["Base.GummyWorms"]           = "ReductionFood",
    ["Base.Hairgel"]              = "ReductionOther",
    ["Base.HardCandies"]          = "ReductionFood",
    ["Base.HiHis"]                = "ReductionFood",
    ["Base.Hinge"]                = "ReductionOther",
    ["Base.Honey"]                = "ReductionFood",
    ["Base.Hotsauce"]             = "ReductionFood",
    ["Base.JamFruit"]             = "ReductionFood",
    ["Base.JamMarmalade"]         = "ReductionFood",
    ["Base.JarLid"]               = "ReductionOther",
    ["Base.JellyBeans"]           = "ReductionFood",
    ["Base.Jujubes"]              = "ReductionFood",
    ["Base.Ketchup"]              = "ReductionFood",
    ["Base.Lard"]                 = "ReductionFood",
    ["Base.Leek"]                 = "ReductionFood",
    ["Base.Lettuce"]              = "ReductionFood",
    ["Base.LicoriceBlack"]        = "ReductionFood",
    ["Base.LicoriceRed"]          = "ReductionFood",
    ["Base.LightBulbBlue"]        = "ReductionOther",
    ["Base.LightBulbCyan"]        = "ReductionOther",
    ["Base.LightBulbGreen"]       = "ReductionOther",
    ["Base.LightBulbMagenta"]     = "ReductionOther",
    ["Base.LightBulbOrange"]      = "ReductionOther",
    ["Base.LightBulbPink"]        = "ReductionOther",
    ["Base.LightBulbPurple"]      = "ReductionOther",
    ["Base.LightBulbRed"]         = "ReductionOther",
    ["Base.LightBulbYellow"]      = "ReductionOther",
    ["Base.Lighter"]              = "ReductionOther",
    ["Base.MakeupEyeshadow"]      = "ReductionOther",
    ["Base.MakeupFoundation"]     = "ReductionOther",
    ["Base.MapleSyrup"]           = "ReductionFood",
    ["Base.Margarine"]            = "ReductionFood",
    ["Base.Marinara"]             = "ReductionFood",
    ["Base.Marshmallows"]         = "ReductionFood",
    ["Base.Matches"]              = "ReductionOther",
    ["Base.MetalPipe"]            = "ReductionMetal",
    ["Base.MotionSensor"]         = "ReductionOther",
    ["Base.Mustard"]              = "ReductionFood",
    ["Base.Nails"]                = "ReductionMetal",
    ["Base.OatsRaw"]              = "ReductionFood",
    ["Base.OilOlive"]             = "ReductionFood",
    ["Base.OilVegetable"]         = "ReductionFood",
    ["Base.Onion"]                = "ReductionFood",
    ["Base.PancakeMix"]           = "ReductionOther",
    ["Base.PaperclipBox"]         = "ReductionOther",
    ["Base.Pasta"]                = "ReductionFood",
    ["Base.PeanutButter"]         = "ReductionFood",
    ["Base.Pepper"]               = "ReductionFood",
    ["Base.PepperHabanero"]       = "ReductionFood",
    ["Base.PepperJalapeno"]       = "ReductionFood",
    ["Base.Pickles"]              = "ReductionFood",
    ["Base.Pillow"]               = "ReductionOther",
    ["Base.Pills"]                = "ReductionMedical",
    ["Base.PillsAntiDep"]         = "ReductionMedical",
    ["Base.PillsBeta"]            = "ReductionMedical",
    ["Base.PillsSleepingTablets"] = "ReductionMedical",
    ["Base.PillsVitamins"]        = "ReductionMedical",
    ["Base.Plank"]                = "ReductionWood",
    ["Base.Plonkies"]             = "ReductionFood",
    ["Base.Popcorn"]              = "ReductionFood",
    ["Base.Pretzel"]              = "ReductionFood",
    ["Base.QuaggaCakes"]          = "ReductionFood",
    ["Base.Ramen"]                = "ReductionFood",
    ["Base.Receiver"]             = "ReductionOther",
    ["Base.Remote"]               = "ReductionOther",
    ["Base.Rice"]                 = "ReductionFood",
    ["Base.RiceVinegar"]          = "ReductionFood",
    ["Base.RockCandy"]            = "ReductionFood",
    ["Base.Salami"]               = "ReductionFood",
    ["Base.Salt"]                 = "ReductionFood",
    ["Base.ScrapMetal"]           = "ReductionMetal",
    ["Base.Screws"]               = "ReductionMetal",
    ["Base.SheetMetal"]           = "ReductionMetal",
    ["Base.SmallSheetMetal"]      = "ReductionMetal",
    ["Base.SnoGlobes"]            = "ReductionFood",
    ["Base.Soap2"]                = "ReductionOther",
    ["Base.Soysauce"]             = "ReductionFood",
    ["Base.Sparklers"]            = "ReductionOther",
    ["Base.Sponge"]               = "ReductionOther",
    ["Base.Spoon"]                = "ReductionOther",
    ["Base.Sugar"]                = "ReductionFood",
    ["Base.SugarBrown"]           = "ReductionFood",
    ["Base.Tarp"]                 = "ReductionOther",
    ["Base.Teabag2"]              = "ReductionFood",
    ["Base.Timer"]                = "ReductionOther",
    ["Base.TimerCrafted"]         = "ReductionOther",
    ["Base.Tissue"]               = "ReductionMedical",
    ["Base.ToiletPaper"]          = "ReductionOther",
    ["Base.TomatoPaste"]          = "ReductionFood",
    ["Base.Toothbrush"]           = "ReductionOther",
    ["Base.TortillaChips"]        = "ReductionFood",
    ["Base.TriggerCrafted"]       = "ReductionOther",
    ["Base.Twine"]                = "ReductionOther",
    ["Base.UnusableWood"]         = "ReductionWood",
    ["Base.WeldingRods"]          = "ReductionOther",
    ["Base.WildEggs"]             = "ReductionFood",
    ["Base.Wire"]                 = "ReductionMetal",
    ["Base.Woodglue"]             = "ReductionOther",
    ["Base.Yeast"]                = "ReductionOther",
    ["Base.Yoghurt"]              = "ReductionFood",
    ["Base.Zucchini"]             = "ReductionFood",
    ["Radio.ElectricWire"]        = "ReductionOther",
    ["Radio.RadioReceiver"]       = "ReductionOther",
    ["Radio.RadioTransmitter"]    = "ReductionOther",
    ["farming.Cabbage"]           = "ReductionFood",
    ["farming.MayonnaiseFull"]    = "ReductionFood",
    ["farming.Potato"]            = "ReductionFood",
    ["farming.RedRadish"]         = "ReductionFood",
    ["farming.RemouladeFull"]     = "ReductionFood",
    ["farming.Tomato"]            = "ReductionFood",
}
