----------
--ESTRAL--
----------

BU = BU or {}

BU.Bundles = {
    ["BundleUp.PlankR"]         = { base = "Base.Plank",          count = 5  },
    ["BundleUp.PlankSR"]        = { base = "Base.Plank",          count = 5  },
    ["BundleUp.SheetMetalR"]    = { base = "Base.SheetMetal",     count = 5  },
    ["BundleUp.SheetMetalSR"]   = { base = "Base.SheetMetal",     count = 5  },
    ["BundleUp.IronPipesR"]     = { base = "Base.MetalPipe",      count = 5  },
    ["BundleUp.IronPipesSR"]    = { base = "Base.MetalPipe",      count = 5  },
    ["BundleUp.IronBarR"]       = { base = "Base.IronBar",        count = 5  },
    ["BundleUp.IronBarSR"]      = { base = "Base.IronBar",        count = 5  },
    ["BundleUp.SteelRodR"]      = { base = "Base.MetalBar",       count = 5  },
    ["BundleUp.SteelRodSR"]     = { base = "Base.MetalBar",       count = 5  },
    ["BundleUp.PlankLR"]        = { base = "Base.Plank",          count = 10 },
    ["BundleUp.PlankLSR"]       = { base = "Base.Plank",          count = 10 },
    ["BundleUp.SheetMetalLR"]   = { base = "Base.SheetMetal",     count = 10 },
    ["BundleUp.SheetMetalLSR"]  = { base = "Base.SheetMetal",     count = 10 },
    ["BundleUp.IronPipesLR"]    = { base = "Base.MetalPipe",      count = 10 },
    ["BundleUp.IronPipesLSR"]   = { base = "Base.MetalPipe",      count = 10 },
    ["BundleUp.IronBarLR"]      = { base = "Base.IronBar",        count = 10 },
    ["BundleUp.IronBarLSR"]     = { base = "Base.IronBar",        count = 10 },
    ["BundleUp.SteelRodLR"]     = { base = "Base.MetalBar",       count = 10 },
    ["BundleUp.SteelRodLSR"]    = { base = "Base.MetalBar",       count = 10 },
    ["BundleUp.GasCanR"]        = { base = "Base.PetrolCan",      count = 4  },
    ["BundleUp.GasCanSR"]       = { base = "Base.PetrolCan",      count = 4  },
    ["BundleUp.GasCanFullR"]    = { base = "Base.PetrolCan",      count = 4, fluid = 10 },
    ["BundleUp.GasCanFullSR"]   = { base = "Base.PetrolCan",      count = 4, fluid = 10 },

    ["BundleUp.TreeBranchR"]     = { base = "Base.TreeBranch2",  count = 5  },
    ["BundleUp.TreeBranchSR"]    = { base = "Base.TreeBranch2",  count = 5  },
    ["BundleUp.TreeBranchLR"]    = { base = "Base.TreeBranch2",  count = 10 },
    ["BundleUp.TreeBranchLSR"]   = { base = "Base.TreeBranch2",  count = 10 },
    ["BundleUp.WoodenRodR"]      = { base = "Base.WoodenStick2", count = 5  },
    ["BundleUp.WoodenRodSR"]     = { base = "Base.WoodenStick2", count = 5  },
    ["BundleUp.WoodenRodLR"]     = { base = "Base.WoodenStick2", count = 10 },
    ["BundleUp.WoodenRodLSR"]    = { base = "Base.WoodenStick2", count = 10 },
    ["BundleUp.LargeBranchR"]    = { base = "Base.LargeBranch",  count = 5  },
    ["BundleUp.LargeBranchSR"]   = { base = "Base.LargeBranch",  count = 5  },
    ["BundleUp.LargeBranchLR"]   = { base = "Base.LargeBranch",  count = 10 },
    ["BundleUp.LargeBranchLSR"]  = { base = "Base.LargeBranch",  count = 10 },
    ["BundleUp.SaplingR"]        = { base = "Base.Sapling",      count = 5  },
    ["BundleUp.SaplingSR"]       = { base = "Base.Sapling",      count = 5  },
    ["BundleUp.SaplingLR"]       = { base = "Base.Sapling",      count = 10 },
    ["BundleUp.SaplingLSR"]      = { base = "Base.Sapling",      count = 10 },
    ["BundleUp.LongStickR"]      = { base = "Base.LongStick",    count = 5  },
    ["BundleUp.LongStickSR"]     = { base = "Base.LongStick",    count = 5  },
    ["BundleUp.LongStickLR"]     = { base = "Base.LongStick",    count = 10 },
    ["BundleUp.LongStickLSR"]    = { base = "Base.LongStick",    count = 10 },
    ["BundleUp.MediumHandleR"]   = { base = "Base.Handle",       count = 5  },
    ["BundleUp.MediumHandleSR"]  = { base = "Base.Handle",       count = 5  },
    ["BundleUp.MediumHandleLR"]  = { base = "Base.Handle",       count = 10 },
    ["BundleUp.MediumHandleLSR"] = { base = "Base.Handle",       count = 10 },
    ["BundleUp.LargeHandleR"]    = { base = "Base.LongHandle",   count = 5  },
    ["BundleUp.LargeHandleSR"]   = { base = "Base.LongHandle",   count = 5  },
    ["BundleUp.LargeHandleLR"]   = { base = "Base.LongHandle",   count = 10 },
    ["BundleUp.LargeHandleLSR"]  = { base = "Base.LongHandle",   count = 10 },
    ["BundleUp.LeadPipeR"]       = { base = "Base.LeadPipe",     count = 5  },
    ["BundleUp.LeadPipeSR"]      = { base = "Base.LeadPipe",     count = 5  },
    ["BundleUp.LeadPipeLR"]      = { base = "Base.LeadPipe",     count = 10 },
    ["BundleUp.LeadPipeLSR"]     = { base = "Base.LeadPipe",     count = 10 },
    ["BundleUp.CopperSheetR"]    = { base = "Base.CopperSheet",  count = 5  },
    ["BundleUp.CopperSheetSR"]   = { base = "Base.CopperSheet",  count = 5  },
    ["BundleUp.CopperSheetLR"]   = { base = "Base.CopperSheet",  count = 10 },
    ["BundleUp.CopperSheetLSR"]  = { base = "Base.CopperSheet",  count = 10 },
    ["BundleUp.GoldSheetR"]      = { base = "Base.GoldSheet",    count = 5  },
    ["BundleUp.GoldSheetSR"]     = { base = "Base.GoldSheet",    count = 5  },
    ["BundleUp.GoldSheetLR"]     = { base = "Base.GoldSheet",    count = 10 },
    ["BundleUp.GoldSheetLSR"]    = { base = "Base.GoldSheet",    count = 10 },

    ["BundleUp.NailsBox_Small"]   = { base = "Base.Nails",        count = 25  },
    ["BundleUp.NailsBox_Medium"]  = { base = "Base.Nails",        count = 50  },
    ["BundleUp.ScrewsBox_Small"]  = { base = "Base.Screws",       count = 25  },
    ["BundleUp.ScrewsBox_Medium"] = { base = "Base.Screws",       count = 50  },
    ["BundleUp.GoldScrap_Small"]  = { base = "Base.GoldScrap",    count = 50  },
    ["BundleUp.GoldScrap_Large"]  = { base = "Base.GoldScrap",    count = 100 },
    ["BundleUp.SilverScrap_Small"]= { base = "Base.SilverScrap",  count = 50  },
    ["BundleUp.SilverScrap_Large"]= { base = "Base.SilverScrap",  count = 100 },
    ["BundleUp.Coke_Small"]       = { base = "Base.Coke",         count = 50  },
    ["BundleUp.Coke_Large"]       = { base = "Base.Coke",         count = 100 },
    ["BundleUp.PenBox_Black"]     = { base = "Base.Pen",          count = 10  },
    ["BundleUp.PenBox_Blue"]      = { base = "Base.BluePen",      count = 10  },
    ["BundleUp.PenBox_Red"]       = { base = "Base.RedPen",       count = 10  },
    ["BundleUp.PenBox_Green"]     = { base = "Base.GreenPen",     count = 10  },

    ["BundleUp.WireCable_Small"]  = { base = "Base.Wire",           count = 5  },
    ["BundleUp.WireCable_Large"]  = { base = "Base.Wire",           count = 10 },
    ["BundleUp.SmallMetalSheetS"] = { base = "Base.SmallSheetMetal", count = 5  },
    ["BundleUp.SmallMetalSheetL"] = { base = "Base.SmallSheetMetal", count = 10 },
    ["BundleUp.GingerAleSP"]      = { base = "Base.Pop3",          count = 6  },
    ["BundleUp.SodaPack"]         = { base = "Base.Pop2",          count = 6  },
    ["BundleUp.DietSodaPack"]     = { base = "Base.Pop",           count = 6  },
    ["BundleUp.BlueberrySP"]      = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.BubblegumSP"]      = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.GrapeSP"]          = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.LimeSP"]           = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.OrangeSP"]         = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.PineappleSP"]      = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.StrawberrySP"]     = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.VarietyPack"]      = { base = "Base.SodaCan",        count = 6  },
    ["BundleUp.StoneBlockPack"]   = { base = "Base.StoneBlock",     count = 10 },

    ["BundleUp.Sack_Sack"]        = { base = "Base.EmptySandbag",   count = 5  },


    -- tanned dry hides; one pack per source so a piglet hide cannot
    -- come back out of the bundle as an Angus cow.

    ["BundleUp.HideCalfAngusR"]         = { base = "Base.CalfLeather_Angus_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfAngusSR"]        = { base = "Base.CalfLeather_Angus_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfAngusLR"]        = { base = "Base.CalfLeather_Angus_Fur_Tan", count = 10  },
    ["BundleUp.HideCalfAngusLSR"]       = { base = "Base.CalfLeather_Angus_Fur_Tan", count = 10  },
    ["BundleUp.HideCowAngusR"]          = { base = "Base.CowLeather_Angus_Fur_Tan", count = 5   },
    ["BundleUp.HideCowAngusSR"]         = { base = "Base.CowLeather_Angus_Fur_Tan", count = 5   },
    ["BundleUp.HideCowAngusLR"]         = { base = "Base.CowLeather_Angus_Fur_Tan", count = 10  },
    ["BundleUp.HideCowAngusLSR"]        = { base = "Base.CowLeather_Angus_Fur_Tan", count = 10  },
    ["BundleUp.HidePigBlackR"]          = { base = "Base.PigLeather_Black_Fur_Tan", count = 5   },
    ["BundleUp.HidePigBlackSR"]         = { base = "Base.PigLeather_Black_Fur_Tan", count = 5   },
    ["BundleUp.HidePigBlackLR"]         = { base = "Base.PigLeather_Black_Fur_Tan", count = 10  },
    ["BundleUp.HidePigBlackLSR"]        = { base = "Base.PigLeather_Black_Fur_Tan", count = 10  },
    ["BundleUp.HidePigletBlackR"]       = { base = "Base.PigletLeather_Black_Fur_Tan", count = 5   },
    ["BundleUp.HidePigletBlackSR"]      = { base = "Base.PigletLeather_Black_Fur_Tan", count = 5   },
    ["BundleUp.HidePigletBlackLR"]      = { base = "Base.PigletLeather_Black_Fur_Tan", count = 10  },
    ["BundleUp.HidePigletBlackLSR"]     = { base = "Base.PigletLeather_Black_Fur_Tan", count = 10  },
    ["BundleUp.HideCalfHolsteinR"]      = { base = "Base.CalfLeather_Holstein_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfHolsteinSR"]     = { base = "Base.CalfLeather_Holstein_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfHolsteinLR"]     = { base = "Base.CalfLeather_Holstein_Fur_Tan", count = 10  },
    ["BundleUp.HideCalfHolsteinLSR"]    = { base = "Base.CalfLeather_Holstein_Fur_Tan", count = 10  },
    ["BundleUp.HideCowHolsteinR"]       = { base = "Base.CowLeather_Holstein_Fur_Tan", count = 5   },
    ["BundleUp.HideCowHolsteinSR"]      = { base = "Base.CowLeather_Holstein_Fur_Tan", count = 5   },
    ["BundleUp.HideCowHolsteinLR"]      = { base = "Base.CowLeather_Holstein_Fur_Tan", count = 10  },
    ["BundleUp.HideCowHolsteinLSR"]     = { base = "Base.CowLeather_Holstein_Fur_Tan", count = 10  },
    ["BundleUp.HideCalfSimmentalR"]     = { base = "Base.CalfLeather_Simmental_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfSimmentalSR"]    = { base = "Base.CalfLeather_Simmental_Fur_Tan", count = 5   },
    ["BundleUp.HideCalfSimmentalLR"]    = { base = "Base.CalfLeather_Simmental_Fur_Tan", count = 10  },
    ["BundleUp.HideCalfSimmentalLSR"]   = { base = "Base.CalfLeather_Simmental_Fur_Tan", count = 10  },
    ["BundleUp.HideCowSimmentalR"]      = { base = "Base.CowLeather_Simmental_Fur_Tan", count = 5   },
    ["BundleUp.HideCowSimmentalSR"]     = { base = "Base.CowLeather_Simmental_Fur_Tan", count = 5   },
    ["BundleUp.HideCowSimmentalLR"]     = { base = "Base.CowLeather_Simmental_Fur_Tan", count = 10  },
    ["BundleUp.HideCowSimmentalLSR"]    = { base = "Base.CowLeather_Simmental_Fur_Tan", count = 10  },
    ["BundleUp.HideDeerR"]              = { base = "Base.DeerLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideDeerSR"]             = { base = "Base.DeerLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideDeerLR"]             = { base = "Base.DeerLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideDeerLSR"]            = { base = "Base.DeerLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideFawnR"]              = { base = "Base.FawnLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideFawnSR"]             = { base = "Base.FawnLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideFawnLR"]             = { base = "Base.FawnLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideFawnLSR"]            = { base = "Base.FawnLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideRabbitR"]            = { base = "Base.RabbitLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideRabbitSR"]           = { base = "Base.RabbitLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideRabbitLR"]           = { base = "Base.RabbitLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideRabbitLSR"]          = { base = "Base.RabbitLeather_Fur_Tan", count = 10  },
    ["BundleUp.HidePigLandraceR"]       = { base = "Base.PigLeather_Landrace_Fur_Tan", count = 5   },
    ["BundleUp.HidePigLandraceSR"]      = { base = "Base.PigLeather_Landrace_Fur_Tan", count = 5   },
    ["BundleUp.HidePigLandraceLR"]      = { base = "Base.PigLeather_Landrace_Fur_Tan", count = 10  },
    ["BundleUp.HidePigLandraceLSR"]     = { base = "Base.PigLeather_Landrace_Fur_Tan", count = 10  },
    ["BundleUp.HidePigletLandraceR"]    = { base = "Base.PigletLeather_Landrace_Fur_Tan", count = 5   },
    ["BundleUp.HidePigletLandraceSR"]   = { base = "Base.PigletLeather_Landrace_Fur_Tan", count = 5   },
    ["BundleUp.HidePigletLandraceLR"]   = { base = "Base.PigletLeather_Landrace_Fur_Tan", count = 10  },
    ["BundleUp.HidePigletLandraceLSR"]  = { base = "Base.PigletLeather_Landrace_Fur_Tan", count = 10  },
    ["BundleUp.HideLambR"]              = { base = "Base.LambLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideLambSR"]             = { base = "Base.LambLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideLambLR"]             = { base = "Base.LambLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideLambLSR"]            = { base = "Base.LambLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideSheepR"]             = { base = "Base.SheepLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideSheepSR"]            = { base = "Base.SheepLeather_Fur_Tan", count = 5   },
    ["BundleUp.HideSheepLR"]            = { base = "Base.SheepLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideSheepLSR"]           = { base = "Base.SheepLeather_Fur_Tan", count = 10  },
    ["BundleUp.HideRabbitGreyR"]        = { base = "Base.RabbitLeather_Grey_Fur_Tan", count = 5   },
    ["BundleUp.HideRabbitGreySR"]       = { base = "Base.RabbitLeather_Grey_Fur_Tan", count = 5   },
    ["BundleUp.HideRabbitGreyLR"]       = { base = "Base.RabbitLeather_Grey_Fur_Tan", count = 10  },
    ["BundleUp.HideRabbitGreyLSR"]      = { base = "Base.RabbitLeather_Grey_Fur_Tan", count = 10  },
    ["BundleUp.HideRaccoonR"]           = { base = "Base.RaccoonLeather_Grey_Fur_Tan", count = 5   },
    ["BundleUp.HideRaccoonSR"]          = { base = "Base.RaccoonLeather_Grey_Fur_Tan", count = 5   },
    ["BundleUp.HideRaccoonLR"]          = { base = "Base.RaccoonLeather_Grey_Fur_Tan", count = 10  },
    ["BundleUp.HideRaccoonLSR"]         = { base = "Base.RaccoonLeather_Grey_Fur_Tan", count = 10  },
    ["BundleUp.HideCrudeLargeR"]        = { base = "Base.Leather_Crude_Large_Tan", count = 5   },
    ["BundleUp.HideCrudeLargeSR"]       = { base = "Base.Leather_Crude_Large_Tan", count = 5   },
    ["BundleUp.HideCrudeLargeLR"]       = { base = "Base.Leather_Crude_Large_Tan", count = 10  },
    ["BundleUp.HideCrudeLargeLSR"]      = { base = "Base.Leather_Crude_Large_Tan", count = 10  },
    ["BundleUp.HideCrudeMediumR"]       = { base = "Base.Leather_Crude_Medium_Tan", count = 5   },
    ["BundleUp.HideCrudeMediumSR"]      = { base = "Base.Leather_Crude_Medium_Tan", count = 5   },
    ["BundleUp.HideCrudeMediumLR"]      = { base = "Base.Leather_Crude_Medium_Tan", count = 10  },
    ["BundleUp.HideCrudeMediumLSR"]     = { base = "Base.Leather_Crude_Medium_Tan", count = 10  },
    ["BundleUp.HideCrudeSmallR"]        = { base = "Base.Leather_Crude_Small_Tan", count = 5   },
    ["BundleUp.HideCrudeSmallSR"]       = { base = "Base.Leather_Crude_Small_Tan", count = 5   },
    ["BundleUp.HideCrudeSmallLR"]       = { base = "Base.Leather_Crude_Small_Tan", count = 10  },
    ["BundleUp.HideCrudeSmallLSR"]      = { base = "Base.Leather_Crude_Small_Tan", count = 10  },


    -- drinks are weighed full: IsFull on the pack input is what guarantees it,
    -- so the litres count toward the pack the way they do for full gas cans.

    ["BundleUp.WhiskeyPack"]             = { base = "Base.Whiskey", count = 6  , fluid = 1.0  },
    ["BundleUp.VodkaPack"]               = { base = "Base.Vodka", count = 6  , fluid = 1.0  },
    ["BundleUp.RumPack"]                 = { base = "Base.Rum", count = 6  , fluid = 1.0  },
    ["BundleUp.GinPack"]                 = { base = "Base.Gin", count = 6  , fluid = 1.0  },
    ["BundleUp.TequilaPack"]             = { base = "Base.Tequila", count = 6  , fluid = 1.0  },
    ["BundleUp.BrandyPack"]              = { base = "Base.Brandy", count = 6  , fluid = 1.0  },
    ["BundleUp.ScotchPack"]              = { base = "Base.Scotch", count = 6  , fluid = 1.0  },
    ["BundleUp.SherryPack"]              = { base = "Base.Sherry", count = 6  , fluid = 1.0  },
    ["BundleUp.PortPack"]                = { base = "Base.Port", count = 6  , fluid = 1.0  },
    ["BundleUp.VermouthPack"]            = { base = "Base.Vermouth", count = 6  , fluid = 1.0  },
    ["BundleUp.CiderPack"]               = { base = "Base.Cider", count = 6  , fluid = 1.0  },
    ["BundleUp.CuracaoPack"]             = { base = "Base.Curacao", count = 6  , fluid = 1.0  },
    ["BundleUp.GrenadinePack"]           = { base = "Base.Grenadine", count = 6  , fluid = 1.0  },
    ["BundleUp.CoffeeLiquerPack"]        = { base = "Base.CoffeeLiquer", count = 6  , fluid = 1.0  },
    ["BundleUp.WineWhitePack"]           = { base = "Base.Wine", count = 6  , fluid = 1.0  },
    ["BundleUp.WineRedPack"]             = { base = "Base.Wine2", count = 6  , fluid = 1.0  },
    ["BundleUp.WineAgedPack"]            = { base = "Base.WineAged", count = 6  , fluid = 1.0  },
    ["BundleUp.WineBoxPack"]             = { base = "Base.WineBox", count = 6  , fluid = 1.0  },
    ["BundleUp.WineScrewtopPack"]        = { base = "Base.WineScrewtop", count = 6  , fluid = 1.0  },
    ["BundleUp.ChampagnePack"]           = { base = "Base.Champagne", count = 6  , fluid = 1.0  },
    ["BundleUp.BeerImportedPack"]        = { base = "Base.BeerImported", count = 6  , fluid = 0.3  },
    ["BundleUp.JuiceBoxGrapePack"]       = { base = "Base.JuiceBox", count = 6  , fluid = 0.2  },
    ["BundleUp.JuiceBoxApplePack"]       = { base = "Base.JuiceBoxApple", count = 6  , fluid = 0.2  },
    ["BundleUp.JuiceBoxFruitpunchPack"]  = { base = "Base.JuiceBoxFruitpunch", count = 6  , fluid = 0.2  },
    ["BundleUp.JuiceBoxOrangePack"]      = { base = "Base.JuiceBoxOrange", count = 6  , fluid = 0.2  },
    ["BundleUp.JuiceCranberryPack"]      = { base = "Base.JuiceCranberry", count = 6  , fluid = 1.0  },
    ["BundleUp.JuiceFruitpunchPack"]     = { base = "Base.JuiceFruitpunch", count = 6  , fluid = 1.0  },
    ["BundleUp.JuiceGrapePack"]          = { base = "Base.JuiceGrape", count = 6  , fluid = 1.0  },
    ["BundleUp.JuiceLemonPack"]          = { base = "Base.JuiceLemon", count = 6  , fluid = 1.0  },
    ["BundleUp.JuiceOrangePack"]         = { base = "Base.JuiceOrange", count = 6  , fluid = 1.0  },
    ["BundleUp.JuiceTomatoPack"]         = { base = "Base.JuiceTomato", count = 6  , fluid = 1.0  },
    ["BundleUp.MilkPack"]                = { base = "Base.Milk", count = 6  , fluid = 1.0  },
    ["BundleUp.MilkBottlePack"]          = { base = "Base.MilkBottle", count = 6  , fluid = 1.0  },
    ["BundleUp.MilkSmallPack"]           = { base = "Base.Milk_Personalsized", count = 6  , fluid = 0.25 },
    ["BundleUp.MilkChocSmallPack"]       = { base = "Base.MilkChocolate_Personalsized", count = 6  , fluid = 0.25 },


    -- aggregate bags are drainables; IsFull on the tie recipe is what keeps a
    -- part-used bag from coming back out of the bundle full.

    ["BundleUp.SandbagR"]           = { base = "Base.Sandbag", count = 5   },
    ["BundleUp.SandbagSR"]          = { base = "Base.Sandbag", count = 5   },
    ["BundleUp.SandbagLR"]          = { base = "Base.Sandbag", count = 10  },
    ["BundleUp.SandbagLSR"]         = { base = "Base.Sandbag", count = 10  },
    ["BundleUp.DirtbagR"]           = { base = "Base.Dirtbag", count = 5   },
    ["BundleUp.DirtbagSR"]          = { base = "Base.Dirtbag", count = 5   },
    ["BundleUp.DirtbagLR"]          = { base = "Base.Dirtbag", count = 10  },
    ["BundleUp.DirtbagLSR"]         = { base = "Base.Dirtbag", count = 10  },
    ["BundleUp.ClaybagR"]           = { base = "Base.Claybag", count = 5   },
    ["BundleUp.ClaybagSR"]          = { base = "Base.Claybag", count = 5   },
    ["BundleUp.ClaybagLR"]          = { base = "Base.Claybag", count = 10  },
    ["BundleUp.ClaybagLSR"]         = { base = "Base.Claybag", count = 10  },
    ["BundleUp.GravelbagR"]         = { base = "Base.Gravelbag", count = 5   },
    ["BundleUp.GravelbagSR"]        = { base = "Base.Gravelbag", count = 5   },
    ["BundleUp.GravelbagLR"]        = { base = "Base.Gravelbag", count = 10  },
    ["BundleUp.GravelbagLSR"]       = { base = "Base.Gravelbag", count = 10  },
    ["BundleUp.CompostBagR"]        = { base = "Base.CompostBag", count = 5   },
    ["BundleUp.CompostBagSR"]       = { base = "Base.CompostBag", count = 5   },
    ["BundleUp.CompostBagLR"]       = { base = "Base.CompostBag", count = 10  },
    ["BundleUp.CompostBagLSR"]      = { base = "Base.CompostBag", count = 10  },
    ["BundleUp.GrassBagR"]          = { base = "Base.GrassBag", count = 5   },
    ["BundleUp.GrassBagSR"]         = { base = "Base.GrassBag", count = 5   },
    ["BundleUp.GrassBagLR"]         = { base = "Base.GrassBag", count = 10  },
    ["BundleUp.GrassBagLSR"]        = { base = "Base.GrassBag", count = 10  },
    ["BundleUp.AnimalFeedBagR"]     = { base = "Base.AnimalFeedBag", count = 5   },
    ["BundleUp.AnimalFeedBagSR"]    = { base = "Base.AnimalFeedBag", count = 5   },
    ["BundleUp.AnimalFeedBagLR"]    = { base = "Base.AnimalFeedBag", count = 10  },
    ["BundleUp.AnimalFeedBagLSR"]   = { base = "Base.AnimalFeedBag", count = 10  },
    ["BundleUp.FertilizerBagR"]     = { base = "Base.Fertilizer", count = 5   },
    ["BundleUp.FertilizerBagSR"]    = { base = "Base.Fertilizer", count = 5   },
    ["BundleUp.FertilizerBagLR"]    = { base = "Base.Fertilizer", count = 10  },
    ["BundleUp.FertilizerBagLSR"]   = { base = "Base.Fertilizer", count = 10  },
    ["BundleUp.ConcretePowderR"]    = { base = "Base.ConcretePowder", count = 5   },
    ["BundleUp.ConcretePowderSR"]   = { base = "Base.ConcretePowder", count = 5   },
    ["BundleUp.ConcretePowderLR"]   = { base = "Base.ConcretePowder", count = 10  },
    ["BundleUp.ConcretePowderLSR"]  = { base = "Base.ConcretePowder", count = 10  },
    ["BundleUp.PlasterPowderR"]     = { base = "Base.PlasterPowder", count = 5   },
    ["BundleUp.PlasterPowderSR"]    = { base = "Base.PlasterPowder", count = 5   },
    ["BundleUp.PlasterPowderLR"]    = { base = "Base.PlasterPowder", count = 10  },
    ["BundleUp.PlasterPowderLSR"]   = { base = "Base.PlasterPowder", count = 10  },
    ["BundleUp.WallpaperPasteR"]    = { base = "Base.WallpaperPastePowder", count = 5   },
    ["BundleUp.WallpaperPasteSR"]   = { base = "Base.WallpaperPastePowder", count = 5   },
    ["BundleUp.WallpaperPasteLR"]   = { base = "Base.WallpaperPastePowder", count = 10  },
    ["BundleUp.WallpaperPasteLSR"]  = { base = "Base.WallpaperPastePowder", count = 10  },
    ["BundleUp.GlassPanelR"]        = { base = "Base.GlassPanel", count = 5   },
    ["BundleUp.GlassPanelSR"]       = { base = "Base.GlassPanel", count = 5   },
    ["BundleUp.GlassPanelLR"]       = { base = "Base.GlassPanel", count = 10  },
    ["BundleUp.GlassPanelLSR"]      = { base = "Base.GlassPanel", count = 10  },
    ["BundleUp.LargePlankR"]        = { base = "Base.LargePlank", count = 5   },
    ["BundleUp.LargePlankSR"]       = { base = "Base.LargePlank", count = 5   },
    ["BundleUp.LargePlankLR"]       = { base = "Base.LargePlank", count = 10  },
    ["BundleUp.LargePlankLSR"]      = { base = "Base.LargePlank", count = 10  },
    ["BundleUp.FlatStoneSack"]      = { base = "Base.FlatStone", count = 10  },
    ["BundleUp.LargeStoneSack"]     = { base = "Base.LargeStone", count = 10  },
    ["BundleUp.SharpedStoneSack"]   = { base = "Base.SharpedStone", count = 25  },
    ["BundleUp.ClaySack"]           = { base = "Base.Clay", count = 25  },

}

BU.BaseCategory = {
    ["Base.Nails"]           = "ReductionMetal",
    ["Base.Screws"]          = "ReductionMetal",
    ["Base.GoldScrap"]       = "ReductionMetal",
    ["Base.SilverScrap"]     = "ReductionMetal",
    ["Base.Wire"]            = "ReductionMetal",
    ["Base.SmallSheetMetal"] = "ReductionMetal",
    ["Base.SheetMetal"]      = "ReductionMetal",
    ["Base.MetalPipe"]       = "ReductionMetal",
    ["Base.IronBar"]         = "ReductionMetal",
    ["Base.MetalBar"]        = "ReductionMetal",
    ["Base.LeadPipe"]        = "ReductionMetal",
    ["Base.CopperSheet"]     = "ReductionMetal",
    ["Base.GoldSheet"]       = "ReductionMetal",
    ["Base.SodaCan"]         = "ReductionMetal",
    ["Base.Pop"]             = "ReductionMetal",
    ["Base.Pop2"]            = "ReductionMetal",
    ["Base.Pop3"]            = "ReductionMetal",
    ["Base.Plank"]           = "ReductionWood",
    ["Base.TreeBranch2"]     = "ReductionWood",
    ["Base.WoodenStick2"]    = "ReductionWood",
    ["Base.LargeBranch"]     = "ReductionWood",
    ["Base.Sapling"]         = "ReductionWood",
    ["Base.LongStick"]       = "ReductionWood",
    ["Base.Handle"]          = "ReductionWood",
    ["Base.LongHandle"]      = "ReductionWood",
    -- coke is forge fuel, not timber; it rides the wood slider with charcoal.
    ["Base.Coke"]            = "ReductionWood",
    ["Base.StoneBlock"]      = "ReductionStone",
    ["Base.PetrolCan"]       = "ReductionOther",
    ["Base.CalfLeather_Angus_Fur_Tan"]          = "ReductionLeather",
    ["Base.CowLeather_Angus_Fur_Tan"]           = "ReductionLeather",
    ["Base.PigLeather_Black_Fur_Tan"]           = "ReductionLeather",
    ["Base.PigletLeather_Black_Fur_Tan"]        = "ReductionLeather",
    ["Base.CalfLeather_Holstein_Fur_Tan"]       = "ReductionLeather",
    ["Base.CowLeather_Holstein_Fur_Tan"]        = "ReductionLeather",
    ["Base.CalfLeather_Simmental_Fur_Tan"]      = "ReductionLeather",
    ["Base.CowLeather_Simmental_Fur_Tan"]       = "ReductionLeather",
    ["Base.DeerLeather_Fur_Tan"]                = "ReductionLeather",
    ["Base.FawnLeather_Fur_Tan"]                = "ReductionLeather",
    ["Base.RabbitLeather_Fur_Tan"]              = "ReductionLeather",
    ["Base.PigLeather_Landrace_Fur_Tan"]        = "ReductionLeather",
    ["Base.PigletLeather_Landrace_Fur_Tan"]     = "ReductionLeather",
    ["Base.LambLeather_Fur_Tan"]                = "ReductionLeather",
    ["Base.SheepLeather_Fur_Tan"]               = "ReductionLeather",
    ["Base.RabbitLeather_Grey_Fur_Tan"]         = "ReductionLeather",
    ["Base.RaccoonLeather_Grey_Fur_Tan"]        = "ReductionLeather",
    ["Base.Leather_Crude_Large_Tan"]            = "ReductionLeather",
    ["Base.Leather_Crude_Medium_Tan"]           = "ReductionLeather",
    ["Base.Leather_Crude_Small_Tan"]            = "ReductionLeather",
    ["Base.Whiskey"]                            = "ReductionFood",
    ["Base.Vodka"]                              = "ReductionFood",
    ["Base.Rum"]                                = "ReductionFood",
    ["Base.Gin"]                                = "ReductionFood",
    ["Base.Tequila"]                            = "ReductionFood",
    ["Base.Brandy"]                             = "ReductionFood",
    ["Base.Scotch"]                             = "ReductionFood",
    ["Base.Sherry"]                             = "ReductionFood",
    ["Base.Port"]                               = "ReductionFood",
    ["Base.Vermouth"]                           = "ReductionFood",
    ["Base.Cider"]                              = "ReductionFood",
    ["Base.Curacao"]                            = "ReductionFood",
    ["Base.Grenadine"]                          = "ReductionFood",
    ["Base.CoffeeLiquer"]                       = "ReductionFood",
    ["Base.Wine"]                               = "ReductionFood",
    ["Base.Wine2"]                              = "ReductionFood",
    ["Base.WineAged"]                           = "ReductionFood",
    ["Base.WineBox"]                            = "ReductionFood",
    ["Base.WineScrewtop"]                       = "ReductionFood",
    ["Base.Champagne"]                          = "ReductionFood",
    ["Base.BeerImported"]                       = "ReductionMetal",
    ["Base.JuiceBox"]                           = "ReductionFood",
    ["Base.JuiceBoxApple"]                      = "ReductionFood",
    ["Base.JuiceBoxFruitpunch"]                 = "ReductionFood",
    ["Base.JuiceBoxOrange"]                     = "ReductionFood",
    ["Base.JuiceCranberry"]                     = "ReductionFood",
    ["Base.JuiceFruitpunch"]                    = "ReductionFood",
    ["Base.JuiceGrape"]                         = "ReductionFood",
    ["Base.JuiceLemon"]                         = "ReductionFood",
    ["Base.JuiceOrange"]                        = "ReductionFood",
    ["Base.JuiceTomato"]                        = "ReductionFood",
    ["Base.Milk"]                               = "ReductionFood",
    ["Base.MilkBottle"]                         = "ReductionFood",
    ["Base.Milk_Personalsized"]                 = "ReductionFood",
    ["Base.MilkChocolate_Personalsized"]        = "ReductionFood",
    ["Base.Sandbag"]                            = "ReductionOther",
    ["Base.Dirtbag"]                            = "ReductionOther",
    ["Base.Claybag"]                            = "ReductionOther",
    ["Base.Gravelbag"]                          = "ReductionOther",
    ["Base.CompostBag"]                         = "ReductionOther",
    ["Base.GrassBag"]                           = "ReductionOther",
    ["Base.AnimalFeedBag"]                      = "ReductionOther",
    ["Base.Fertilizer"]                         = "ReductionOther",
    ["Base.ConcretePowder"]                     = "ReductionOther",
    ["Base.PlasterPowder"]                      = "ReductionOther",
    ["Base.WallpaperPastePowder"]               = "ReductionOther",
    ["Base.GlassPanel"]                         = "ReductionOther",
    ["Base.LargePlank"]                         = "ReductionWood",
    ["Base.FlatStone"]                          = "ReductionStone",
    ["Base.LargeStone"]                         = "ReductionStone",
    ["Base.SharpedStone"]                       = "ReductionStone",
    ["Base.Clay"]                               = "ReductionOther",
}

-- A pack's base is usually a vanilla item, but a nested pack names another
-- pack instead. Walking down to the vanilla item at the bottom gives the
-- category lookup something it can match.
local MAX_DEPTH = 16

function BU.resolveBase(fullType)
    local def = BU.Bundles[fullType]
    if not def then
        return nil
    end

    local base = def.base
    for _ = 1, MAX_DEPTH do
        local parent = BU.Bundles[base]
        if not parent then
            return base
        end
        base = parent.base
    end
    return nil
end

function BU.nestingDepth(fullType)
    local def = BU.Bundles[fullType]
    for depth = 0, MAX_DEPTH do
        if not def then
            return depth
        end
        local parent = BU.Bundles[def.base]
        if not parent then
            return depth
        end
        def = parent
    end
    return MAX_DEPTH
end
