----------
--ESTRAL--
----------

local ProceduralDistributions_list = ProceduralDistributions.list
local table_insert = table.insert

local function applyDistribution(items, weights)
    for tableName, weight in pairs(weights) do
        local distribution = ProceduralDistributions_list[tableName]
        local containerItems = distribution and distribution.items
        if containerItems then
            for i = 1, #items do
                table_insert(containerItems, items[i])
                table_insert(containerItems, weight)
            end
        end
    end
end

local PACK_ITEMS = {
    "BundleUp.BlueberrySP",
    "BundleUp.BubblegumSP",
    "BundleUp.GrapeSP",
    "BundleUp.LimeSP",
    "BundleUp.OrangeSP",
    "BundleUp.PineappleSP",
    "BundleUp.StrawberrySP",
    "BundleUp.GingerAleSP",
    "BundleUp.VarietyPack",
}

local PACK_WEIGHTS = {
    BandPracticeFridge  = 0.1,
    BarCounterMisc      = 0.2,
    BeerGardenCounter   = 0.01,
    BreweryCans         = 0.45,
    CafeteriaDrinks     = 0.2,
    CrateBeer           = 0.05,
    FridgeBeer          = 0.01,
    FridgeGarage        = 0.1,
    FridgeGeneric       = 0.005,
    FridgeHoarder       = 0.1,
    FridgeHunter        = 0.9,
    FridgeSoda          = 0.55,
    FridgeTrailerPark   = 0.01,
    JuiceStandFridge    = 1.65,
    KitchenBottles      = 0.45,
    LiquorStoreBeer     = 0.1,
    NolansFridge        = 0.01,
    SafehouseBooze      = 0.1,
    SafehouseFood       = 0.45,
    SafehouseFood_Mid   = 0.1,
    SafehouseFridge     = 0.45,
    SafehouseFridge_Mid = 0.1,
    StoreShelfDrinks    = 1.65,
    TheatreDrinks       = 0.45,
}

applyDistribution(PACK_ITEMS, PACK_WEIGHTS)

local FOOD_ITEMS = {
    "BundleUp.BBQSauceCarton",
    "BundleUp.BalsamicVinegarCarton",
    "BundleUp.BeefJerkyCarton",
    "BundleUp.CandyCaramelsCarton",
    "BundleUp.CandyCornCarton",
    "BundleUp.CandyFruitSlicesCarton",
    "BundleUp.CandyGummyfishCarton",
    "BundleUp.CandyMolassesCarton",
    "BundleUp.CandyNovapopsCarton",
    "BundleUp.CandycaneCarton",
    "BundleUp.ChocolateCarton",
    "BundleUp.ChocolateChipsCarton",
    "BundleUp.Chocolate_ButterchunkersCarton",
    "BundleUp.Chocolate_CandyCarton",
    "BundleUp.Chocolate_CrackleCarton",
    "BundleUp.Chocolate_DeuxCarton",
    "BundleUp.Chocolate_GalacticDairyCarton",
    "BundleUp.Chocolate_RoysPBPucksCarton",
    "BundleUp.Chocolate_SmirkersCarton",
    "BundleUp.Chocolate_SnikSnakCarton",
    "BundleUp.CilantroDriedCarton",
    "BundleUp.CookieChocolateChipCarton",
    "BundleUp.CookieJellyCarton",
    "BundleUp.CookiesChocolateCarton",
    "BundleUp.CookiesOatmealCarton",
    "BundleUp.CookiesShortbreadCarton",
    "BundleUp.Cornflour2Carton",
    "BundleUp.Cornmeal2Carton",
    "BundleUp.CrackersCarton",
    "BundleUp.CrispsCarton",
    "BundleUp.Crisps2Carton",
    "BundleUp.Crisps3Carton",
    "BundleUp.Crisps4Carton",
    "BundleUp.DehydratedMeatStickCarton",
    "BundleUp.Dip_SalsaCarton",
    "BundleUp.DriedBlackBeansCarton",
    "BundleUp.DriedChickpeasCarton",
    "BundleUp.DriedKidneyBeansCarton",
    "BundleUp.DriedLentilsCarton",
    "BundleUp.DriedSplitPeasCarton",
    "BundleUp.Flour2Carton",
    "BundleUp.GrahamCrackersCarton",
    "BundleUp.GranolaBarCarton",
    "BundleUp.GumCarton",
    "BundleUp.GummyBearsCarton",
    "BundleUp.GummyWormsCarton",
    "BundleUp.HardCandiesCarton",
    "BundleUp.HiHisCarton",
    "BundleUp.HoneyCarton",
    "BundleUp.JamFruitCarton",
    "BundleUp.JamMarmaladeCarton",
    "BundleUp.JellyBeansCarton",
    "BundleUp.JujubesCarton",
    "BundleUp.KetchupCarton",
    "BundleUp.LardCarton",
    "BundleUp.LavenderPetalsDriedCarton",
    "BundleUp.LicoriceBlackCarton",
    "BundleUp.LicoriceRedCarton",
    "BundleUp.MacaroniCarton",
    "BundleUp.MapleSyrupCarton",
    "BundleUp.MargarineCarton",
    "BundleUp.MarinaraCarton",
    "BundleUp.MarshmallowsCarton",
    "BundleUp.MustardCarton",
    "BundleUp.OatsRawCarton",
    "BundleUp.OilOliveCarton",
    "BundleUp.OilVegetableCarton",
    "BundleUp.PeanutButterCarton",
    "BundleUp.PepperCarton",
    "BundleUp.PepperHabaneroCarton",
    "BundleUp.PepperJalapenoCarton",
    "BundleUp.PepperJalapenoDriedCarton",
    "BundleUp.PlonkiesCarton",
    "BundleUp.PopcornCarton",
    "BundleUp.PorkRindsCarton",
    "BundleUp.PowderedGarlicCarton",
    "BundleUp.PowderedOnionCarton",
    "BundleUp.PretzelCarton",
    "BundleUp.RamenCarton",
    "BundleUp.RiceVinegarCarton",
    "BundleUp.RockCandyCarton",
    "BundleUp.ScoutCookiesCarton",
    "BundleUp.SeasoningSaltCarton",
    "BundleUp.Seasoning_BasilCarton",
    "BundleUp.Seasoning_ChivesCarton",
    "BundleUp.Seasoning_CilantroCarton",
    "BundleUp.Seasoning_OreganoCarton",
    "BundleUp.Seasoning_ParsleyCarton",
    "BundleUp.Seasoning_RosemaryCarton",
    "BundleUp.Seasoning_SageCarton",
    "BundleUp.Seasoning_ThymeCarton",
    "BundleUp.SesameOilCarton",
    "BundleUp.SnoGlobesCarton",
    "BundleUp.SoysauceCarton",
    "BundleUp.SugarCarton",
    "BundleUp.SugarBrownCarton",
    "BundleUp.Teabag2Carton",
    "BundleUp.ThymeDriedCarton",
    "BundleUp.YoghurtCarton",
    "BundleUp.BasilDriedCarton",
    "BundleUp.BellPepperCarton",
    "BundleUp.BlackSageDriedCarton",
    "BundleUp.BroccoliCarton",
    "BundleUp.ButterCarton",
    "BundleUp.CabbageCarton",
    "BundleUp.CarrotsCarton",
    "BundleUp.CauliflowerCarton",
    "BundleUp.CerealCarton",
    "BundleUp.ChamomileDriedCarton",
    "BundleUp.CheeseCarton",
    "BundleUp.ChivesDriedCarton",
    "BundleUp.ChocoCakesCarton",
    "BundleUp.ChocolateCoveredCoffeeBeansCarton",
    "BundleUp.CinnamonRollCarton",
    "BundleUp.CocoaPowderCarton",
    "BundleUp.Coffee2Carton",
    "BundleUp.CommonMallowDriedCarton",
    "BundleUp.CookiesSugarCarton",
    "BundleUp.CornCarton",
    "BundleUp.CrispyRiceSquareCarton",
    "BundleUp.CucumberCarton",
    "BundleUp.Dip_NachoCheeseCarton",
    "BundleUp.Dip_RanchCarton",
    "BundleUp.DogFoodBagCrate",
    "BundleUp.DriedWhiteBeansCarton",
    "BundleUp.EggplantCarton",
    "BundleUp.GarlicCarton",
    "BundleUp.GingerbreadmanCarton",
    "BundleUp.GinsengCarton",
    "BundleUp.GreenpeasCarton",
    "BundleUp.HotsauceCarton",
    "BundleUp.KaleCarton",
    "BundleUp.LeekCarton",
    "BundleUp.LettuceCarton",
    "BundleUp.MarigoldDriedCarton",
    "BundleUp.MayonnaiseFullCarton",
    "BundleUp.MintHerbDriedCarton",
    "BundleUp.OnionCarton",
    "BundleUp.OreganoDriedCarton",
    "BundleUp.ParsleyDriedCarton",
    "BundleUp.PastaCarton",
    "BundleUp.PepperHabaneroDriedCarton",
    "BundleUp.PicklesCarton",
    "BundleUp.PotatoCarton",
    "BundleUp.QuaggaCakesCarton",
    "BundleUp.RedRadishCarton",
    "BundleUp.RemouladeFullCarton",
    "BundleUp.RiceCarton",
    "BundleUp.RosePetalsDriedCarton",
    "BundleUp.RosemaryDriedCarton",
    "BundleUp.SageDriedCarton",
    "BundleUp.SalamiCarton",
    "BundleUp.SaltCarton",
    "BundleUp.SoybeansCarton",
    "BundleUp.SpinachCarton",
    "BundleUp.SquashCarton",
    "BundleUp.SugarBeetCarton",
    "BundleUp.SweetPotatoCarton",
    "BundleUp.TomatoCarton",
    "BundleUp.TomatoPasteCarton",
    "BundleUp.TortillaChipsCarton",
    "BundleUp.TurkeyEggCarton",
    "BundleUp.TurnipCarton",
    "BundleUp.WildEggsCarton",
    "BundleUp.WildGarlicDriedCarton",
    "BundleUp.ZucchiniCarton",
}

local FOOD_WEIGHTS = {
    GigamartCannedFood      = 0.3,
    GigamartDryGoods        = 0.3,
    GigamartBakingMisc      = 0.2,
    GigamartCandy           = 0.2,
    GigamartCrisps          = 0.2,
    GigamartSauce           = 0.2,
    GigamartSpices          = 0.15,
    GigamartBottles         = 0.15,
    GigamartBBQ             = 0.1,
    GroceryStandFruits1     = 0.15,
    GroceryStandFruits2     = 0.15,
    GroceryStandFruits3     = 0.15,
    GroceryStandVegetables1 = 0.15,
    GroceryStandVegetables2 = 0.15,
    GroceryStandVegetables3 = 0.15,
    GroceryStandVegetables4 = 0.15,
    GroceryStandVegetables5 = 0.15,
    GroceryStandLettuce     = 0.15,
    GroceryStorageCrate1    = 0.4,
    GroceryStorageCrate2    = 0.4,
    GroceryStorageCrate3    = 0.4,
}

applyDistribution(FOOD_ITEMS, FOOD_WEIGHTS)

local MATERIALS_ITEMS = {
    "BundleUp.PlankR",
    "BundleUp.PlankSR",
    "BundleUp.SheetMetalR",
    "BundleUp.SheetMetalSR",
    "BundleUp.IronPipesR",
    "BundleUp.IronPipesSR",
    "BundleUp.IronBarR",
    "BundleUp.IronBarSR",
    "BundleUp.PlankLR",
    "BundleUp.PlankLSR",
    "BundleUp.SheetMetalLR",
    "BundleUp.SheetMetalLSR",
    "BundleUp.IronPipesLR",
    "BundleUp.IronPipesLSR",
    "BundleUp.IronBarLR",
    "BundleUp.IronBarLSR",
    "BundleUp.NailsBox_Small",
    "BundleUp.NailsBox_Medium",
    "BundleUp.ScrewsBox_Small",
    "BundleUp.ScrewsBox_Medium",
    "BundleUp.WireCable_Small",
    "BundleUp.WireCable_Large",
    "BundleUp.SmallMetalSheetS",
    "BundleUp.SmallMetalSheetL",
    "BundleUp.StoneBlockPack",
    "BundleUp.NutsBoltsBox",
    "BundleUp.HingeBox",
    "BundleUp.DoorknobBox",
    "BundleUp.SmallHandleBox",
    "BundleUp.WeldingRodsBox",
    "BundleUp.WhetstoneBox",
    "BundleUp.BuckleBox",
}

local MATERIALS_WEIGHTS = {
    ToolStoreCarpentry   = 0.3,
    ToolStoreMetalwork   = 0.3,
    ToolStoreTools       = 0.2,
    ToolStoreMisc        = 0.2,
    ToolStoreAccessories = 0.15,
    ToolStoreHandles     = 0.15,
}

applyDistribution(MATERIALS_ITEMS, MATERIALS_WEIGHTS)

local GENERAL_ITEMS = {
    "BundleUp.AdhesiveTapeBoxCrate",
    "BundleUp.AluminumBox",
    "BundleUp.AmplifierBox",
    "BundleUp.BakingSodaBox",
    "BundleUp.BatteryBoxCrate",
    "BundleUp.ButterKnifeBox",
    "BundleUp.ButtonBox",
    "BundleUp.CandleBoxCrate",
    "BundleUp.CorrectionFluidBox",
    "BundleUp.DuctTapeBoxCrate",
    "BundleUp.ElectricWireBox",
    "BundleUp.EpoxyBox",
    "BundleUp.FiberglassTapeBox",
    "BundleUp.ForkBox",
    "BundleUp.Garbagebag_boxBox",
    "BundleUp.GasmaskFilterBox",
    "BundleUp.GlueBox",
    "BundleUp.GravyMixBox",
    "BundleUp.HairgelBox",
    "BundleUp.Hairspray2Box",
    "BundleUp.InsectRepellentBox",
    "BundleUp.JarLidBox",
    "BundleUp.LightBulbBlueBox",
    "BundleUp.LightBulbBoxCrate",
    "BundleUp.LightBulbCyanBox",
    "BundleUp.LightBulbGreenBox",
    "BundleUp.LightBulbMagentaBox",
    "BundleUp.LightBulbOrangeBox",
    "BundleUp.LightBulbPinkBox",
    "BundleUp.LightBulbPurpleBox",
    "BundleUp.LightBulbRedBox",
    "BundleUp.LightBulbYellowBox",
    "BundleUp.LighterBox",
    "BundleUp.LighterBBQBox",
    "BundleUp.LighterDisposableBox",
    "BundleUp.MagnesiumFirestarterBox",
    "BundleUp.MakeupEyeshadowBox",
    "BundleUp.MakeupFoundationBox",
    "BundleUp.MatchesBox",
    "BundleUp.MotionSensorBox",
    "BundleUp.PagerBox",
    "BundleUp.PancakeMixBox",
    "BundleUp.PaperNapkins2Box",
    "BundleUp.PaperclipBoxCrate",
    "BundleUp.PillowBox",
    "BundleUp.RadioReceiverBox",
    "BundleUp.RadioTransmitterBox",
    "BundleUp.RatPoisonBox",
    "BundleUp.ReceiverBox",
    "BundleUp.RemoteBox",
    "BundleUp.SlugRepellentBox",
    "BundleUp.SmallAnimalBoneBox",
    "BundleUp.Soap2Box",
    "BundleUp.SparklersBox",
    "BundleUp.SpongeBox",
    "BundleUp.SpoonBox",
    "BundleUp.TarpBox",
    "BundleUp.Thread_AramidBox",
    "BundleUp.Thread_SinewBox",
    "BundleUp.TimerBox",
    "BundleUp.TimerCraftedBox",
    "BundleUp.TissueBoxCrate",
    "BundleUp.ToiletPaperBox",
    "BundleUp.ToothbrushBox",
    "BundleUp.TriggerCraftedBox",
    "BundleUp.TwineBox",
    "BundleUp.Vinegar2Box",
    "BundleUp.Vinegar_JugBox",
    "BundleUp.WoodglueBox",
    "BundleUp.YeastBox",
    "BundleUp.ZiptiesBox",
    "BundleUp.PenBox_Black",
    "BundleUp.PenBox_Blue",
    "BundleUp.PenBox_Red",
    "BundleUp.PenBox_Green",
}

local GENERAL_WEIGHTS = {
    GigamartLightbulb        = 0.3,
    GigamartCleaning         = 0.25,
    GigamartToiletries       = 0.25,
    GigamartPaper            = 0.2,
    GigamartHousewares       = 0.2,
    GigamartPots             = 0.15,
    GigamartHouseElectronics = 0.15,
    GigamartSchool           = 0.15,
    GigamartTools            = 0.15,
}

applyDistribution(GENERAL_ITEMS, GENERAL_WEIGHTS)

local FISHING_SUPPLY_ITEMS = {
    "BundleUp.FishingHookBoxCrate",
    "BundleUp.FishingLineBox",
    "BundleUp.JigLureBox",
    "BundleUp.MinnowLureBox",
    "BundleUp.PremiumFishingLineBox",
}

local FISHING_SUPPLY_WEIGHTS = {
    FishingStoreBait = 0.3,
    FishingStoreGear = 0.2,
}

applyDistribution(FISHING_SUPPLY_ITEMS, FISHING_SUPPLY_WEIGHTS)

local MEDICAL_ITEMS = {
    "BundleUp.AlcoholBandageBox",
    "BundleUp.AlcoholWipesBox",
    "BundleUp.AlcoholedCottonBallsBox",
    "BundleUp.PillsBox",
    "BundleUp.PillsAntiDepBox",
    "BundleUp.PillsBetaBox",
    "BundleUp.PillsSleepingTabletsBox",
    "BundleUp.PillsVitaminsBox",
    "BundleUp.TissueBox",
    "BundleUp.WaterPurificationTabletsBox",
    "BundleUp.BandageDirtyBox",
    "BundleUp.DisinfectantBox",
}

local MEDICAL_WEIGHTS = {
    MedicalStorageDrugs = 0.3,
    MedicalClinicDrugs  = 0.25,
    StoreShelfMedical   = 0.2,
    FridgeMedical       = 0.1,
}

applyDistribution(MEDICAL_ITEMS, MEDICAL_WEIGHTS)

local AMMO_ITEMS = {
    "BundleUp.44ClipBox",
    "BundleUp.JS14ClipBox",
    "BundleUp.556ClipBox",
    "BundleUp.45ClipBox",
    "BundleUp.M14ClipBox",
    "BundleUp.9mmClipBox",
}

local AMMO_WEIGHTS = {
    GunStoreAmmunition    = 0.2,
    GunStoreMagsAmmo      = 0.3,
    ArmyStorageAmmunition = 0.2,
    ArmySurplusAmmoBoxes  = 0.15,
    SWATStorageAmmunition = 0.15,
}

applyDistribution(AMMO_ITEMS, AMMO_WEIGHTS)

local FARMING_ITEMS = {
    "BundleUp.BarleyBagSeedPouch",
    "BundleUp.BasilBagSeedPouch",
    "BundleUp.BellPepperBagSeedPouch",
    "BundleUp.BlackSageBagSeedPouch",
    "BundleUp.BroadleafPlantainBagSeedPouch",
    "BundleUp.BroccoliBagSeed2Pouch",
    "BundleUp.CabbageBagSeed2Pouch",
    "BundleUp.CarrotBagSeed2Pouch",
    "BundleUp.CauliflowerBagSeedPouch",
    "BundleUp.ChamomileBagSeedPouch",
    "BundleUp.ChivesBagSeedPouch",
    "BundleUp.CilantroBagSeedPouch",
    "BundleUp.ComfreyBagSeedPouch",
    "BundleUp.CommonMallowBagSeedPouch",
    "BundleUp.CornBagSeedPouch",
    "BundleUp.CucumberBagSeedPouch",
    "BundleUp.FlaxBagSeedPouch",
    "BundleUp.GarlicBagSeedPouch",
    "BundleUp.GreenpeasBagSeedPouch",
    "BundleUp.HabaneroBagSeedPouch",
    "BundleUp.HempBagSeedPouch",
    "BundleUp.HopsBagSeedPouch",
    "BundleUp.JalapenoBagSeedPouch",
    "BundleUp.KaleBagSeedPouch",
    "BundleUp.LavenderBagSeedPouch",
    "BundleUp.LeekBagSeedPouch",
    "BundleUp.LemonGrassBagSeedPouch",
    "BundleUp.LettuceBagSeedPouch",
    "BundleUp.MarigoldBagSeedPouch",
    "BundleUp.MintBagSeedPouch",
    "BundleUp.OnionBagSeedPouch",
    "BundleUp.OreganoBagSeedPouch",
    "BundleUp.ParsleyBagSeedPouch",
    "BundleUp.PoppyBagSeedPouch",
    "BundleUp.PotatoBagSeed2Pouch",
    "BundleUp.PumpkinBagSeedPouch",
    "BundleUp.RedRadishBagSeed2Pouch",
    "BundleUp.RoseBagSeedPouch",
    "BundleUp.RosemaryBagSeedPouch",
    "BundleUp.RyeBagSeedPouch",
    "BundleUp.SageBagSeedPouch",
    "BundleUp.SoybeansBagSeedPouch",
    "BundleUp.SpinachBagSeedPouch",
    "BundleUp.StrewberrieBagSeed2Pouch",
    "BundleUp.SugarBeetBagSeedPouch",
    "BundleUp.SunflowerBagSeedPouch",
    "BundleUp.SweetPotatoBagSeedPouch",
    "BundleUp.ThymeBagSeedPouch",
    "BundleUp.TobaccoBagSeedPouch",
    "BundleUp.TomatoBagSeed2Pouch",
    "BundleUp.TurnipBagSeedPouch",
    "BundleUp.WatermelonBagSeedPouch",
    "BundleUp.WheatBagSeedPouch",
    "BundleUp.WildGarlicBagSeedPouch",
    "BundleUp.ZucchiniBagSeedPouch",
}

local FARMING_WEIGHTS = {
    GardenStoreMisc  = 0.4,
    GardenStoreTools = 0.2,
    GigamartFarming  = 0.2,
}

applyDistribution(FARMING_ITEMS, FARMING_WEIGHTS)

local SCRAP_ITEMS = {
    "BundleUp.AluminumScrapSack",
    "BundleUp.BrassScrapSack",
    "BundleUp.BrokenGlassSack",
    "BundleUp.CharcoalCraftedSack",
    "BundleUp.CopperScrapSack",
    "BundleUp.ElectronicsScrapSack",
    "BundleUp.IronScrapSack",
    "BundleUp.ScrapMetalSack",
    "BundleUp.SplintersSack",
    "BundleUp.SteelScrapSack",
    "BundleUp.UnusableWoodSack",
    "BundleUp.Sack_Sack",
    "BundleUp.CircularSawbladeBox",
    "BundleUp.IronBandBox",
    "BundleUp.IronBandSmallBox",
    "BundleUp.IronBarHalfBox",
    "BundleUp.IronBarQuarterBox",
    "BundleUp.IronBlockBox",
    "BundleUp.IronChunkBox",
    "BundleUp.IronPieceBox",
    "BundleUp.RakeHeadBox",
    "BundleUp.SteelBarHalfBox",
    "BundleUp.SteelBarQuarterBox",
    "BundleUp.SteelBlockBox",
    "BundleUp.SteelChunkBox",
    "BundleUp.SteelPieceBox",
}

local SCRAP_WEIGHTS = {
    WeldingWorkshopMetal = 0.3,
    WeldingWorkshopFuel  = 0.1,
    WeldingWorkshopTools = 0.15,
    MechanicShelfTools   = 0.2,
    MechanicOutfit       = 0.1,
}

applyDistribution(SCRAP_ITEMS, SCRAP_WEIGHTS)

local JEWELRY_ITEMS = {
    "BundleUp.GoldScrap_Small",
    "BundleUp.GoldScrap_Large",
    "BundleUp.SilverScrap_Small",
    "BundleUp.SilverScrap_Large",
    "BundleUp.JewelryPouch_Small",
    "BundleUp.JewelryPouch_Medium",
}

local JEWELRY_WEIGHTS = {
    JewelryGold        = 0.3,
    JewelrySilver      = 0.3,
    JewelryOthers      = 0.2,
    JewelryStorageAll  = 0.2,
}

applyDistribution(JEWELRY_ITEMS, JEWELRY_WEIGHTS)
