----------
--ESTRAL--
----------

local ProceduralDistributions_list = ProceduralDistributions.list
local table_insert = table.insert

local function applyDistribution(items, weights)
    for tableName, weight in pairs(weights) do
        local distribution = ProceduralDistributions_list[tableName]
        local containerItems = distribution and distribution.items
        if containerItems then
            for i = 1, #items do
                table_insert(containerItems, items[i])
                table_insert(containerItems, weight)
            end
        end
    end
end

local PACK_ITEMS = {
    "BundleUp.BlueberrySP",
    "BundleUp.BubblegumSP",
    "BundleUp.GrapeSP",
    "BundleUp.LimeSP",
    "BundleUp.OrangeSP",
    "BundleUp.PineappleSP",
    "BundleUp.StrawberrySP",
    "BundleUp.GingerAleSP",
    "BundleUp.VarietyPack",
}

local PACK_WEIGHTS = {
    BandPracticeFridge  = 0.1,
    BarCounterMisc      = 0.2,
    BeerGardenCounter   = 0.01,
    BreweryCans         = 0.45,
    CafeteriaDrinks     = 0.2,
    CrateBeer           = 0.05,
    FridgeBeer          = 0.01,
    FridgeGarage        = 0.1,
    FridgeGeneric       = 0.005,
    FridgeHoarder       = 0.1,
    FridgeHunter        = 0.9,
    FridgeSoda          = 0.55,
    FridgeTrailerPark   = 0.01,
    JuiceStandFridge    = 1.65,
    KitchenBottles      = 0.45,
    LiquorStoreBeer     = 0.1,
    NolansFridge        = 0.01,
    SafehouseBooze      = 0.1,
    SafehouseFood       = 0.45,
    SafehouseFood_Mid   = 0.1,
    SafehouseFridge     = 0.45,
    SafehouseFridge_Mid = 0.1,
    StoreShelfDrinks    = 1.65,
    TheatreDrinks       = 0.45,
}

applyDistribution(PACK_ITEMS, PACK_WEIGHTS)

local FOOD_ITEMS = {
    "BundleUp.BBQSauceCarton",
    "BundleUp.BalsamicVinegarCarton",
    "BundleUp.BeefJerkyCarton",
    "BundleUp.CandyCaramelsCarton",
    "BundleUp.CandyCornCarton",
    "BundleUp.CandyFruitSlicesCarton",
    "BundleUp.CandyGummyfishCarton",
    "BundleUp.CandyMolassesCarton",
    "BundleUp.CandyNovapopsCarton",
    "BundleUp.CandycaneCarton",
    "BundleUp.ChocolateCarton",
    "BundleUp.ChocolateChipsCarton",
    "BundleUp.Chocolate_ButterchunkersCarton",
    "BundleUp.Chocolate_CandyCarton",
    "BundleUp.Chocolate_CrackleCarton",
    "BundleUp.Chocolate_DeuxCarton",
    "BundleUp.Chocolate_GalacticDairyCarton",
    "BundleUp.Chocolate_RoysPBPucksCarton",
    "BundleUp.Chocolate_SmirkersCarton",
    "BundleUp.Chocolate_SnikSnakCarton",
    "BundleUp.CilantroDriedCarton",
    "BundleUp.CookieChocolateChipCarton",
    "BundleUp.CookieJellyCarton",
    "BundleUp.CookiesChocolateCarton",
    "BundleUp.CookiesOatmealCarton",
    "BundleUp.CookiesShortbreadCarton",
    "BundleUp.Cornflour2Carton",
    "BundleUp.Cornmeal2Carton",
    "BundleUp.CrackersCarton",
    "BundleUp.CrispsCarton",
    "BundleUp.Crisps2Carton",
    "BundleUp.Crisps3Carton",
    "BundleUp.Crisps4Carton",
    "BundleUp.DehydratedMeatStickCarton",
    "BundleUp.Dip_SalsaCarton",
    "BundleUp.DriedBlackBeansCarton",
    "BundleUp.DriedChickpeasCarton",
    "BundleUp.DriedKidneyBeansCarton",
    "BundleUp.DriedLentilsCarton",
    "BundleUp.DriedSplitPeasCarton",
    "BundleUp.Flour2Carton",
    "BundleUp.GrahamCrackersCarton",
    "BundleUp.GranolaBarCarton",
    "BundleUp.GumCarton",
    "BundleUp.GummyBearsCarton",
    "BundleUp.GummyWormsCarton",
    "BundleUp.HardCandiesCarton",
    "BundleUp.HiHisCarton",
    "BundleUp.HoneyCarton",
    "BundleUp.JamFruitCarton",
    "BundleUp.JamMarmaladeCarton",
    "BundleUp.JellyBeansCarton",
    "BundleUp.JujubesCarton",
    "BundleUp.KetchupCarton",
    "BundleUp.LardCarton",
    "BundleUp.LavenderPetalsDriedCarton",
    "BundleUp.LicoriceBlackCarton",
    "BundleUp.LicoriceRedCarton",
    "BundleUp.MacaroniCarton",
    "BundleUp.MapleSyrupCarton",
    "BundleUp.MargarineCarton",
    "BundleUp.MarinaraCarton",
    "BundleUp.MarshmallowsCarton",
    "BundleUp.MustardCarton",
    "BundleUp.OatsRawCarton",
    "BundleUp.OilOliveCarton",
    "BundleUp.OilVegetableCarton",
    "BundleUp.PeanutButterCarton",
    "BundleUp.PepperCarton",
    "BundleUp.PepperHabaneroCarton",
    "BundleUp.PepperJalapenoCarton",
    "BundleUp.PepperJalapenoDriedCarton",
    "BundleUp.PlonkiesCarton",
    "BundleUp.PopcornCarton",
    "BundleUp.PorkRindsCarton",
    "BundleUp.PowderedGarlicCarton",
    "BundleUp.PowderedOnionCarton",
    "BundleUp.PretzelCarton",
    "BundleUp.RamenCarton",
    "BundleUp.RiceVinegarCarton",
    "BundleUp.RockCandyCarton",
    "BundleUp.ScoutCookiesCarton",
    "BundleUp.SeasoningSaltCarton",
    "BundleUp.Seasoning_BasilCarton",
    "BundleUp.Seasoning_ChivesCarton",
    "BundleUp.Seasoning_CilantroCarton",
    "BundleUp.Seasoning_OreganoCarton",
    "BundleUp.Seasoning_ParsleyCarton",
    "BundleUp.Seasoning_RosemaryCarton",
    "BundleUp.Seasoning_SageCarton",
    "BundleUp.Seasoning_ThymeCarton",
    "BundleUp.SesameOilCarton",
    "BundleUp.SnoGlobesCarton",
    "BundleUp.SoysauceCarton",
    "BundleUp.SugarCarton",
    "BundleUp.SugarBrownCarton",
    "BundleUp.Teabag2Carton",
    "BundleUp.ThymeDriedCarton",
    "BundleUp.YoghurtCarton",
    "BundleUp.BasilDriedCarton",
    "BundleUp.BellPepperCarton",
    "BundleUp.BlackSageDriedCarton",
    "BundleUp.BroccoliCarton",
    "BundleUp.ButterCarton",
    "BundleUp.CabbageCarton",
    "BundleUp.CarrotsCarton",
    "BundleUp.CauliflowerCarton",
    "BundleUp.CerealCarton",
    "BundleUp.ChamomileDriedCarton",
    "BundleUp.CheeseCarton",
    "BundleUp.ChivesDriedCarton",
    "BundleUp.ChocoCakesCarton",
    "BundleUp.ChocolateCoveredCoffeeBeansCarton",
    "BundleUp.CinnamonRollCarton",
    "BundleUp.CocoaPowderCarton",
    "BundleUp.Coffee2Carton",
    "BundleUp.CommonMallowDriedCarton",
    "BundleUp.CookiesSugarCarton",
    "BundleUp.CornCarton",
    "BundleUp.CrispyRiceSquareCarton",
    "BundleUp.CucumberCarton",
    "BundleUp.Dip_NachoCheeseCarton",
    "BundleUp.Dip_RanchCarton",
    "BundleUp.DogFoodBagCrate",
    "BundleUp.DriedWhiteBeansCarton",
    "BundleUp.EggplantCarton",
    "BundleUp.GarlicCarton",
    "BundleUp.GingerbreadmanCarton",
    "BundleUp.GinsengCarton",
    "BundleUp.GreenpeasCarton",
    "BundleUp.HotsauceCarton",
    "BundleUp.KaleCarton",
    "BundleUp.LeekCarton",
    "BundleUp.LettuceCarton",
    "BundleUp.MarigoldDriedCarton",
    "BundleUp.MayonnaiseFullCarton",
    "BundleUp.MintHerbDriedCarton",
    "BundleUp.OnionCarton",
    "BundleUp.OreganoDriedCarton",
    "BundleUp.ParsleyDriedCarton",
    "BundleUp.PastaCarton",
    "BundleUp.PepperHabaneroDriedCarton",
    "BundleUp.PicklesCarton",
    "BundleUp.PotatoCarton",
    "BundleUp.QuaggaCakesCarton",
    "BundleUp.RedRadishCarton",
    "BundleUp.RemouladeFullCarton",
    "BundleUp.RiceCarton",
    "BundleUp.RosePetalsDriedCarton",
    "BundleUp.RosemaryDriedCarton",
    "BundleUp.SageDriedCarton",
    "BundleUp.SalamiCarton",
    "BundleUp.SaltCarton",
    "BundleUp.SoybeansCarton",
    "BundleUp.SpinachCarton",
    "BundleUp.SquashCarton",
    "BundleUp.SugarBeetCarton",
    "BundleUp.SweetPotatoCarton",
    "BundleUp.TomatoCarton",
    "BundleUp.TomatoPasteCarton",
    "BundleUp.TortillaChipsCarton",
    "BundleUp.TurkeyEggCarton",
    "BundleUp.TurnipCarton",
    "BundleUp.WildEggsCarton",
    "BundleUp.WildGarlicDriedCarton",
    "BundleUp.ZucchiniCarton",
}

local FOOD_WEIGHTS = {
    GigamartCannedFood      = 0.3,
    GigamartDryGoods        = 0.3,
    GigamartBakingMisc      = 0.2,
    GigamartCandy           = 0.2,
    GigamartCrisps          = 0.2,
    GigamartSauce           = 0.2,
    GigamartSpices          = 0.15,
    GigamartBottles         = 0.15,
    GigamartBBQ             = 0.1,
    GroceryStandFruits1     = 0.15,
    GroceryStandFruits2     = 0.15,
    GroceryStandFruits3     = 0.15,
    GroceryStandVegetables1 = 0.15,
    GroceryStandVegetables2 = 0.15,
    GroceryStandVegetables3 = 0.15,
    GroceryStandVegetables4 = 0.15,
    GroceryStandVegetables5 = 0.15,
    GroceryStandLettuce     = 0.15,
    GroceryStorageCrate1    = 0.4,
    GroceryStorageCrate2    = 0.4,
    GroceryStorageCrate3    = 0.4,
}

applyDistribution(FOOD_ITEMS, FOOD_WEIGHTS)
