#!/usr/bin/env python3
"""Emit the upper pack tiers from the ladders the mod already declares.

Hand-writing a tier means repeating every family member four times over: an
item block, both halves of a pack/unpack recipe, a weight row and a display
name. At ~166 food cartons that is unreadable and unreviewable, so the rungs
above Carton are generated from BU_WeightData_Packs.lua instead.

Output is committed. Re-running with no source change must produce no diff.

    python tools/generate_tiers.py [--check]
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MEDIA = ROOT / "Contents/mods/Vanilla/42/media"

BANNER_SCRIPT = "/*----------*/\n/*--ESTRAL--*/\n/*----------*/\n"
BANNER_LUA = "----------\n--ESTRAL--\n----------\n"
STAMP_LUA = "-- Generated by tools/generate_tiers.py. Do not edit by hand.\n"
STAMP_SCRIPT = "/*-- Generated by tools/generate_tiers.py. Do not edit by hand. --*/\n"

MODULE_HEAD = "\nmodule BundleUp {\n    imports {\n        Base,\n    }\n\n"

# Each rung names the rung it packs, how many of it fit, and the art to wear.
TIERS = [
    {
        "name": "Case",
        "packs": "Carton",
        "per": 4,
        "recipe": "FoodCase",
        "display_category": "Food",
        "tags": "base:ignorezombiedensity",
        "verb": ("Pack Food Cartons in Case", "Open Food Case (4 cartons)"),
        "label": "Case of {}",
        "art": {
            "dry": ("Parcel_ExtraLarge_Food", "Parcel_Food_ExtraLarge"),
            "fresh": ("Parcel_ExtraLarge_Fruit", "Parcel_Produce_ExtraLarge"),
        },
        "on_create": "BUInv.carryFoodAge",
        "on_test": "BUInv.testPackPerishable",
    },
]


def read(path):
    return (MEDIA / path).read_text(encoding="utf-8")


def write(path, text, changed):
    target = MEDIA / path
    old = target.read_text(encoding="utf-8") if target.exists() else None
    if old != text:
        changed.append(str(Path(path)))
        target.write_text(text, encoding="utf-8", newline="\n")


def load_bundles():
    src = read("lua/shared/BU_WeightData.lua") + read("lua/shared/BU_WeightData_Packs.lua")
    bundles, category = {}, {}
    row = r'\["([\w.]+)"\]\s*=\s*\{\s*base\s*=\s*"([\w.]+)"\s*,\s*count\s*=\s*(\d+)'
    for m in re.finditer(row, src):
        bundles[m.group(1)] = (m.group(2), int(m.group(3)))
    for m in re.finditer(r'\["([\w.]+)"\]\s*=\s*"(Reduction\w+)"', src):
        category[m.group(1)] = m.group(2)
    return bundles, category


def resolve_base(bundles, full_type):
    base, count = bundles[full_type]
    for _ in range(16):
        if base not in bundles:
            return base, count
        parent_base, parent_count = bundles[base]
        count *= parent_count
        base = parent_base
    raise RuntimeError("cycle resolving " + full_type)


def food_cartons(bundles, category):
    """Cartons whose contents are food, split by which recipe packs them.

    Membership comes from the recipes rather than the item name: one carton
    is called DogFoodBagCrate, and keying on the suffix drops it silently.
    """
    recipes = read("scripts/recipes/recipes_boxed.txt")

    def members(recipe):
        block = re.search("craftRecipe " + recipe + r"\s*\{.*?\n    \}", recipes, re.S)
        return set(re.findall(r"BundleUp\.\w+", block.group(0))) if block else set()

    kinds = {}
    for kind, recipe in (("dry", "UnpackDryCarton"), ("fresh", "UnpackFreshCarton")):
        for full_type in members(recipe):
            kinds[full_type] = kind

    out = []
    for full_type in sorted(kinds):
        if full_type not in bundles:
            raise RuntimeError(full_type + " is packed by a recipe but has no weight row")
        base, _ = resolve_base(bundles, full_type)
        if category.get(base) != "ReductionFood":
            raise RuntimeError(full_type + " is packed as food but resolves to " + str(base))
        out.append((full_type, kinds[full_type]))
    return out


# Rung names that already appear as item suffixes, longest first so that a
# name ending in both is trimmed by the more specific one.
RUNG_SUFFIXES = ("Carton", "Crate", "Box", "Pack", "Sack", "Pouch")


def strip_rung(stem, expected):
    for suffix in (expected,) + RUNG_SUFFIXES:
        if stem.endswith(suffix):
            return stem[: -len(suffix)]
    return stem


def label_for(carton_type, names, tier):
    """Reuse the carton's own display name so the case reads consistently."""
    carton = names.get(carton_type, "")
    stem = re.sub(r"^(Carton|Box|Pack|Sack|Pouch) of\s+", "", carton).strip()
    return tier["label"].format(stem or carton_type.split(".")[-1])


def carton_rot():
    """DaysFresh / DaysTotallyRotten per carton, read off the cartons themselves.

    A case has to rot on the same schedule as its carton or age stops mapping
    one to one as it moves up and down the ladder.
    """
    out = {}
    for m in re.finditer(r"    item (\w+) \{(.*?)    \}", read("scripts/items/boxed.txt"), re.S):
        fresh = re.search(r"DaysFresh = ([^,\n]+),", m.group(2))
        rotten = re.search(r"DaysTotallyRotten = ([^,\n]+),", m.group(2))
        if fresh and rotten:
            out[m.group(1)] = (fresh.group(1), rotten.group(1))
    return out


def item_block(stem, tier, icon, model, unpack, carton_count, rot):
    weight = round(carton_count * tier["per"] * 0.12, 1)

    if rot:
        kind = (
            "        ItemType = base:food,\n"
            "        CantEat = true,\n"
            "        DaysFresh = " + rot[0] + ",\n"
            "        DaysTotallyRotten = " + rot[1] + ",\n"
        )
        open_with = "        OpeningRecipe = " + unpack + ",\n"
    else:
        kind = "        ItemType = base:normal,\n"
        open_with = "        DoubleClickRecipe = " + unpack + ",\n"

    return (
        "    item " + stem + tier["name"] + " {\n"
        "        DisplayCategory = " + tier["display_category"] + ",\n"
        + kind +
        "        Weight = " + str(weight) + ",\n"
        "        Icon = " + icon + ",\n"
        "        WorldStaticModel = " + model + ",\n"
        "        Tags = " + tier["tags"] + ",\n"
        + open_with +
        "    }"
    )


def recipe_pair(tier, pack, unpack, rows):
    lower = ";".join(c for c, _ in rows)
    upper = ";".join(n for _, n in rows)
    pack_map = "\n".join("            " + n + " = " + c + "," for c, n in rows)
    unpack_map = "\n".join("            " + c + " = " + n + "," for c, n in rows)
    per = str(tier["per"])
    return (
        "    craftRecipe " + pack + " {\n"
        "        timedAction = PackingBox,\n"
        "        time = 50,\n"
        "        Tags = InHandCraft;CanBeDoneInDark,\n"
        "        onCreate = " + tier["on_create"] + ",\n"
        "        onTest = " + tier["on_test"] + ",\n"
        "        category = Packing,\n"
        "        inputs {\n"
        "            item " + per + " [" + lower + "] flags[IsExclusive;ItemCount] mappers[tierMap],\n"
        "        }\n"
        "        outputs {\n"
        "            item 1 mapper:tierMap,\n"
        "        }\n"
        "        itemMapper tierMap {\n" + pack_map + "\n        }\n"
        "    }\n\n"
        "    craftRecipe " + unpack + " {\n"
        "        timedAction = UnPackBox,\n"
        "        time = 50,\n"
        "        Tags = InHandCraft;CanBeDoneInDark,\n"
        "        onCreate = " + tier["on_create"] + ",\n"
        "        category = Packing,\n"
        "        inputs {\n"
        "            item 1 [" + upper + "] mappers[tierMap],\n"
        "        }\n"
        "        outputs {\n"
        "            item " + per + " mapper:tierMap,\n"
        "        }\n"
        "        itemMapper tierMap {\n" + unpack_map + "\n        }\n"
        "    }"
    )


def build(bundles, category, names):
    items, recipes, weights, item_names, recipe_names = [], [], [], {}, {}
    rot = carton_rot()

    for tier in TIERS:
        pack = "Pack" + tier["recipe"]
        unpack = "Unpack" + tier["recipe"]
        recipe_names[pack], recipe_names[unpack] = tier["verb"]

        rows = []
        for carton, kind in food_cartons(bundles, category):
            stem = strip_rung(carton.split(".", 1)[1], tier["packs"])
            new = "BundleUp." + stem + tier["name"]
            icon, model = tier["art"][kind]
            _, carton_count = bundles[carton]

            items.append(item_block(stem, tier, icon, model, unpack, carton_count,
                                    rot.get(carton.split(".", 1)[1])))
            weights.append(
                'BU.Bundles["' + new + '"] = { base = "' + carton + '", count = '
                + str(tier["per"]) + " }"
            )
            item_names[new] = label_for(carton, names, tier)
            rows.append((carton, new))

        recipes.append(recipe_pair(tier, pack, unpack, rows))

    return items, recipes, weights, item_names, recipe_names


def splice_json(path, generated, changed):
    """Keep hand-written entries in place, park generated ones at the end."""
    existing = json.loads(read(path))
    kept = {k: v for k, v in existing.items() if k not in generated}
    merged = list(kept.items()) + [(k, generated[k]) for k in sorted(generated)]
    body = ",\n".join("  " + json.dumps(k) + ": " + json.dumps(v) for k, v in merged)
    write(path, "{\n" + body + "\n}\n", changed)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if regenerating would change anything")
    args = parser.parse_args()

    bundles, category = load_bundles()
    names = json.loads(read("lua/shared/Translate/EN/ItemName.json"))
    items, recipes, weights, item_names, recipe_names = build(bundles, category, names)

    changed = []
    write("scripts/items/tiered.txt",
          BANNER_SCRIPT + STAMP_SCRIPT + MODULE_HEAD + "\n\n".join(items) + "\n}\n",
          changed)
    write("scripts/recipes/recipes_tiered.txt",
          BANNER_SCRIPT + STAMP_SCRIPT + MODULE_HEAD + "\n\n".join(recipes) + "\n}\n",
          changed)
    write("lua/shared/BU_WeightData_Tiers.lua",
          BANNER_LUA + STAMP_LUA + '\nrequire "BU_WeightData"\n\n'
          "BU = BU or {}\nBU.Bundles = BU.Bundles or {}\n\n"
          + "\n".join(weights) + "\n",
          changed)
    splice_json("lua/shared/Translate/EN/ItemName.json", item_names, changed)
    splice_json("lua/shared/Translate/EN/Recipes.json", recipe_names, changed)

    if args.check:
        if changed:
            print("out of date:\n  " + "\n  ".join(changed), file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0

    print(str(len(item_names)) + " items across " + str(len(TIERS)) + " tier(s)")
    print("changed:\n  " + "\n  ".join(changed) if changed else "no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
